### ISSUE TITLE
Domanda MOOOOLTO urgente

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#100]
Nella nostra progettazione abbiamo deciso di usare il design pattern 'Composite' per la gestione della rubrica degli utenti e questo design pattern (come tutti sapete ;) ) permette di creare strutture gerarchiche, mi riferisco ai sottogruppi di un gruppo. Quest'ultima cosa deve essere memorizzata permanentemente anche nel DB????? Se la risposta è affermativa manca una chiave esterna sull'entità Groups che punta a se stessa. (Relazione RICORSIVA....ma che bello!!!!)

**Comment by diegoberaldin** [comment]
La risposta è affermativa, un gruppo può contenere zero o più gruppi e, poiché un gruppo può avere zero o un padre si configura l'esistenza di una relazione ricorsiva molti-a-uno con totalità parziale in entrambi i versi, da tradurre nel modello relazionale come dici tu: con una foreign key (che però può essere NULL per recuperare la totalità "parziale" dell'associazione diretta) inserendo un attributo Father di tipo `int` che punta al `Group_ID`.
Spero di aver risposto...

**Comment by meneghinello-andrea** [comment]
Hai centrato in pieno il bug che ho riscontrato. Volevo solo capire se stavo dicendo una fesseria. Dopo cena faccio l'upgrade nella specifica tecnica nella sezione che riguarda il database.

**Comment by meneghinello-andrea** [comment]
Invece di avere totalità parziale pensavo totalità totale. Chi sta in cima ha come padre se stesso. Cosa ne dici?

**Comment by meneghinello-andrea** [comment]
Problema corretto. Era come dicevi tu Diego.
