### ISSUE TITLE
[ST] diagrammi classi: aggiungere interfaccia IMessage

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#104]
Nel diagramma della classi della parte server nel componente "Gestione database" bisogna aggiungere l'interfaccia `IMessage`. Le classi che estendono `IMessage` sono `AudioMessage` e `AudioVideoMessage` nel package `server.dao` e `MessageProxy` nel package `server.message`.

I diagrammi delle classi interessati dalla modifica sono, in dettaglio:
- il diagramma generale della sotto-architettura `server`
- il diagramma del componente "Gestione database"
- il diagramma del componente "Gestione segreteria"

**Comment by diegoberaldin** [comment]
Alla fine questa è un duplicato di #112 e se n'è occupata @MissEle, quindi chiudo!
