### ISSUE TITLE
[ST] diagramma componente "Gestione GUI": classe duplicata

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#106]
Esportare nuovamente il package `org::softwaresynthesis::mytalk::clientview::gui`. Attenzione che non ci sia una doppia classe che estende `MainPanel` che ha lo stesso nome. Una deve rimanere `MessagePanel` e l'altra dovrà essere `SearchResultPanel`

**Comment by diegoberaldin** [comment]
Attenzione: prima di prendere in carico questa issue occorre attendere che il team dei progettisti abbia ripensato la sotto-architettura `clientview`, ammesso che si chiami ancora così!

**Comment by diegoberaldin** [comment]
Il diagramma è stato rifatto ex novo per #112 quindi questa può essere chiusa!
