### ISSUE TITLE
[ST] verificare diagrammi di attività dopo le modifiche "correttive" ;)

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#108]

**Comment by diegoberaldin** [comment]
@B1uRay l'hai fatto e non hai trovato nulla che non andasse o non l'hai proprio fatto?

**Comment by B1uRay** [comment]
io non ho trovato particolari problemi....forse nel tentativo di trovare qualcosa da correggere ho inserito un errorino (!!!) ti aggiorno. xD
