### ISSUE TITLE
[PdQ] integrare contenuto delle wiki nel documento

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#109]
Il contenuto da inserire sono [le indicazioni sul Piano di qualifica](https://github.com/SoftwareSynthesis/SoftwareEngineeringProject/wiki/Chi-ha-paura-del-PdQ-cattivo%3F) presenti nelle wiki.

**Comment by diegoberaldin** [comment]
Considerato che:
- nessuno si è dato la pena di leggere la pagina in questione;
- nessuno di è dato pena di aiutare a raccogliere idee;

e che non so se devo interpretare come **indifferenza** o come **parere ostile** questo comportamento, faccio un riassunto e aggiorno il PdQ con quello che si può dire - una versione opportunamente edulcorata - di autovalutazione.

Vorrei solo far notare che:
- le riflessioni sul PdQ sono nate su segnalazione di @Rizzi-Andrea e non perché il sottoscritto abbia le sue ubbie o paranoie o si annoiava e non aveva di meglio da fare;
- le riflessioni su come sono stati svolti i ruoli e usati gli strumenti avrebbero potuto essere davvero utili
  - perché tutti avrebbero dovuto considerare con aria critica l'operato degli altri e sarebbe stato costruttivo
  - per non ripetere continuamente gli stessi errori.

Sono un po' deluso dal fatto che nessuno abbia voluto collaborare, tanto meno la persona che aveva sollevato il problema. Non credo sia il modo corretto di lavorare, anche se c'è di peggio nella vita e abbiamo altri problemi.

**Comment by Rizzi-Andrea** [comment]
Richiede verifica!
