### ISSUE TITLE
[ST] riconsiderare sotto-architettura clientpresenter e clientview

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#111]

**Comment by diegoberaldin** [comment]
Fatto, anche se ne richiedo verifica a qualcuno che sia più lucido di mente... ad esempio @Rizzi-Andrea :smile_cat:

**Comment by Rizzi-Andrea** [comment]
OK BOSS... finisco duw cose sul PdQ e mi ci metto dietro!
