### ISSUE TITLE
[ST] correzione diagrammi delle classi

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#112]
Vanno rivisti ed eventualmente corretti i diagrammi nel file 'Diagrammi classi 2.0'. Prestare molta attenzione al tipo di frecce, alla dimensione del carattere e sopprimere tutti i campi attribute.

**Comment by diegoberaldin** [comment]
Chiuso quanto si poteva fare, ora occorre verifica e completare!
