### ISSUE TITLE
[ST] integrare con vantaggi di Apache Derby (ammesso che ce ne siano)

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#113]

**Comment by diegoberaldin** [comment]
Uno fra tutti che mi sento di sottolineare, è che un DBMS [embedded](http://en.wikipedia.org/wiki/Embedded_database) (come il nostro amato SQLite) che non richiede l'esecuzione di un demone/servizio esterno ma è integrato nell'applicazione stessa.

**Comment by Rizzi-Andrea** [comment]
Scusa Diego ma non ho capito cosa intendi... perchè parli di SQLite?
