### ISSUE TITLE
[ST] aggiornamento chiavi primarie del database

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#114]
Gli oggetti che lavorano con il framework Hibernate non permettono di modificare la chiave primaria assegnata ad un oggetto una volta che questa è stata creata. Risolvere il problema

**Comment by meneghinello-andrea** [comment]
Soluzione proposta: introduzione nel database di chiavi primarie sintetiche e definizione di funzioni sql per la generazione delle stesse.

**Comment by diegoberaldin** [comment]
Approvato :+1:

**Comment by meneghinello-andrea** [comment]
Procedo!!!

**Comment by diegoberaldin** [comment]
La situazione ieri (15/02) è cambiata nuovamente :smiling_imp: come stabilito in #120. Chiudo questa e lascio aperta l'altra!
