### ISSUE TITLE
[ST] completamento diagrammi design-pattern

### ISSUE THREAD

**Issue by MissEle** [SoftwareSynthesis/SoftwareEngineeringProject#115]

**Comment by diegoberaldin** [comment]
Mancavano i seguenti diagrammi dei pattern:
-Facade del server
-Factory del facade

Mancano i seguenti diagrammi delle componenti:
- Facade Server
- Gesitone connessione
  -Facade Presenter
  -Gesitone Comunicazione

**Comment by diegoberaldin** [comment]
Obsoleto, i diagrammi sono stati ultimati a parte (es. #112)!
