### ISSUE TITLE
[PdQ] verifica sezione "autovalutazione"

### ISSUE THREAD

**Issue by B1uRay** [SoftwareSynthesis/SoftwareEngineeringProject#116]
Non me ne voglia l'autore (Rizzi) ma il capitolo relativo all'Autovalutazione (che ho appena corretto in qualche sua parte da buon verificatore :-P ) nonostante tratti tematiche relative alla qualità, risulta un pò "fuori luogo" in un documento specifico e incentrato su tematiche quali qualità di prodotto e di processo.

Tali considerazioni verrebbero più gradite (forse) in un documento indipendente visto che esprime considerazioni più coerenti ad una "riunione consuntiva" che delle norme qualitative vere e proprie.

E' solo una mia idea, conforme tra l'altro a quanto scritto proprio dal nostro Spriz! XD
Che ne pensate? :-)

EDIT: Un'alternativa potrebbe consistere nello spostare la parte relativa a "considerazioni sui rapporti interpersonali" nella sezione 2 delle NdP che tratta i medesimi argomenti.

**Comment by diegoberaldin** [comment]
L'alternativa sarebbe quindi di mettere quella parte come se fosse il verbale di un incontro?

**Comment by B1uRay** [comment]
o come editato portare una parte dentro le norme di progetto.

**Comment by Rizzi-Andrea** [comment]
Sono d'accordo con B1uRay ;). Diciamo che per metà lasciamo nel PdQ mentre l'altra metà, ossia le considerazioni sui rapporti interpersonali, le mettiamo nel norme! :)

**Comment by diegoberaldin** [comment]
Allora vada per lo spostamento! Cambio l'oggetto dell'issue e la classifico come "todo"

**Comment by B1uRay** [comment]
Ho spostato la parte sulle Norme di Progetto, rileggendolo mi sembra molto più ordinato e coerente ora.
Stavo anche valutando di sistemare meglio nel PdQ quanto scritto da Rizzi (che leggendolo e rileggendolo comincio a credere sia una cosa che Tullio potrebbe apprezzare davvero, funzionano i "consigli" scritti nelle Wiki! :P ) in modo da integrarlo meglio. Magari se qualcuno ci da un occhiata "esterna" e mi da qualche consiglio/aiuto ve ne sarei grato. :-)

**Comment by Rizzi-Andrea** [comment]
Ho provato a riprendere in considerazione quello che ho scritto, ma non ho trovato spunti intelligenti si come cambiarli. Tu di preciso cosa intendevi con "sistemare meglio in moda da integrarlo"???

**Comment by B1uRay** [comment]
No no tranquillo, intendevo "esterna" al PdQ (quindi escludi chi l'ha scritto: me-te-Diego) proprio perchè SE ci sono problemi saltano subito all'occhio. ;-)

Poi ribadisco, è più un discorso di "stile d'integrazione" che una modifica vera e propria, magari sono solo pippe mentali mie, anzi, ne attenderei con ansia la conferma!! :P

**Comment by diegoberaldin** [comment]
Un'altra cosa che si potrebbe fare è metterlo in Appendice al PdQ, dato che si tratta di considerazioni che non si riferiscono tanto al "piano" in sé quanto ai problemi emersi in fase di attuazione del piano stesso..

**Comment by B1uRay** [comment]
:+1:
