### ISSUE TITLE
[NdP] cosa-vuole-riccardin + rendere il documento più "procedurale"

### ISSUE THREAD

**Issue by B1uRay** [SoftwareSynthesis/SoftwareEngineeringProject#117]
Sto dando un occhiata al documento redatto dal Dott.Schivo ormai due mesi orsono, cercando di capire gli argomenti e le norme "non ancora sufficientemente procedurali per essere pienamente efficaci" [cit].

Ho interpretato tale commento con una semplice "riorganizzazione" a livello di indice (es. l'ambiente documentale viene trattato nel cap 4, mentre la verifica dei documenti nel cap 9) e integrazione con qualche informazione e dettaglio aggiuntivo.
Chi ha qualche altra idea o interpretazione più illuminante si faccia pure avanti plz. :-)

**Comment by diegoberaldin** [comment]
Ricordo a tutti che anche #68 aveva uno scopo simile per l'analisi dei requisiti e che c'è la famosa [pagina delle wiki](https://github.com/SoftwareSynthesis/SoftwareEngineeringProject/wiki/Sondaggi) per lasciare le proprie opinioni. Io non so esattamente quando e come ma mi ripropongo di scriverci qualcosa questo weekend...

**Comment by B1uRay** [comment]
Dopo una rivisitazione del documento sarebbe necessario che un verificatore si prenda mezz'oretta per valutare le modifica, non so se ora sono più procedurali (non ho avuto particolari illuminazioni in tre giorni) ma ho integrato le varie parti prendendo spunto dai "soliti noti" e ampliando molti argomenti. Forse ora sono più chiare. Ditemi voi. :-)

**Comment by diegoberaldin** [comment]
Ti riferisci a a3009813bd3a6a5107415501720b609f5d7bb665 per i cambiamenti apportati? Se dici verifico io, dato che da domani 22/02 divento verificatore...

**Comment by B1uRay** [comment]
Quelli dell'ultimo commit sono rifiniture marginali, in ogni caso si, sono le modifiche fatte fino a quel punto (per gli altri aggiornamenti basta rifarsi agli aggiornamenti precedenti/confrontare con le vecchie NdP). :-)

**Comment by diegoberaldin** [comment]
Ho dovuto scavare un po' ma li ho trovati, erano:
- 7597438ffb619a14e96e083740bc5feece0ecd6f
- e1e0717857bdef5278d6b6966acb8e98db8cb1a9
- 4c6aac36bac694eaa9f3591402d6f6996a26d7df

Verifico io oggi :)

**Comment by diegoberaldin** [comment]
@B1uRay ottimo lavoro! Hai aggiunto un sacco di roba che più procedurale di così si muore! Non pensavo che avessi fatto così tanto e in così poco tempo!

Questa cosa mi ha fatto sorridere (presa dalle norme di codifica per JavaScript)

> il codice di ogni funzione sarà anticipato da una pre-condizione che ne spieghi concisamente lo scopo

in quanto implica che si sappia esattamente cosa faccia ogni funzione e rabbrividisco al solo pensiero perché più mi avventuro in quell'oscuro labirinto più vedo codice del cui scopo/funzionamento non ho la benché minima idea!

**Comment by B1uRay** [comment]
eh, ho avuto tanto "tempo libero" da sfruttare per questo documento, mi è sembrato il minimo farcirlo di tutto quel che trovavo! xD
Sulla "frase" sono stato anche troppo buono, gli "altri" avevano pre-post-invariante...QUELLO fa rabbrividire! :P 

Si può chiudere l'issue?

**Comment by diegoberaldin** [comment]
Sì sì saremo par carità! Ancora rabbrividisco...
