### ISSUE TITLE
[PdQ]/[NdP] test: questi sconosciuti

### ISSUE THREAD

**Issue by B1uRay** [SoftwareSynthesis/SoftwareEngineeringProject#118]
Specificare nel piano di qualifica (o eventualmente modificare paragrafo sui test sulle NdP) il funzionamento di JUnit e QUnit e relativa implementazione.

**Comment by diegoberaldin** [comment]
Per come la vedo io non bisognerebbe "normare" l'utilizzo di questi strumenti in NdP e stabilire la strategia di test in PdQ.  Per i test di accettazione e di sistema, invece, alla fine se non sbaglio si era deciso di lasciarli in AR e di inserire al massimo in PdQ un riferimento, giusto?

**Comment by B1uRay** [comment]
Confermo. Era appunto un TODO per tenere traccia del "da farsi". ;-)
