### ISSUE TITLE
[ST] aggiunta nuovi strumenti e relativi vantaggi alla sezione 3

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#119]
Gli strumenti da integrare sono:
- TomCat
- il web server Apache
- MySQL
  So che l'ha fatta @Rizzi-Andrea ma non so dove sia il testo!

**Comment by Rizzi-Andrea** [comment]
Perdonami, visto che stavi lavorando te sulle specifiche l'ho inserito in un txt che ho qui in locale. Provvederò il prima posibile ad inserirlo nelle specifiche e a fare commit... anche se ho molta... molta... paura XP. Più che altro in merito al testo mi sembra di aver scritto banalità... ma più di queste non sono riuscito a trovare nulla. Se giudicherete il lavoro insufficiente ci spenderò altro tempo il prima possibile ;)

**Comment by diegoberaldin** [comment]
Non importa per le banalità, ti sembra che siano state scritte cose intelligenti sul resto? In ogni caso non devi pensare che sarai giudicato per quel che scrivi, io se avessi il tuo testo davanti e non mi soddisfacesse appieno penserei a cosa aggiungere e come migliorarlo e lo farei io stesso o ti suggerirei cosa aggiungere come ho fatto per Derby. **Mai e poi mai** penserei «ma guarda te cos'ha scritto quel pagliaccio!» e cancellerei tutto venendomi poi a lamentare!

Riguardo a sincronizzare i tuoi commit in remoto non so che dire, non trovo le parole giuste. Lunedì perdiamo 10 minuti tu ed io, tema della chiacchierata «Git su GNU/Linux».
PS. Quando ero amministratore ti avevo messo a modo mio nelle condizioni di fare commit come tutti gli altri, ma siccome "era troppo lungo il diagramma" non si capiva bene o non l'hai guardato tutto. Dammi una seconda possibilità, stavolta senza UML.

**Comment by Rizzi-Andrea** [comment]
Ahah ok BOSS ;)
