### ISSUE TITLE
[ST] progettazione database: associazione ricorsiva in Groups

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#122]
Nel nuovo modello di rubrica non ha più senso che i gruppi siano contenuti in altri gruppi. Pertanto:
- nella progettazione concettuale non sussiste più l'associazione ricorsiva Groups-Groups uno a molti
- nella progettazione logica non dovrebbe più esistere la chiave esterna `Father` che punta all'id di un gruppo.

È corretto?

**Comment by diegoberaldin** [comment]
[RANTING]
Non so quanti "cadaveri" del passato ci siano, ogni volta che butto l'occhio me ne salta fuori uno. Questo serva a tutti di lezione sul fatto che **è meglio spendere più tempo a discutere di una cosa tutti ed essere tutti convinti piuttosto che apportare sterzate in corso d'opera che fanno perdere MOLTO più tempo e introducono una valanga di errori a cascata**!
[/RANTING]

**Comment by Rizzi-Andrea** [comment]
Onestamente io ho le idee confuse su cosa sia ora la rubrica. Cmq scrivo per darti ragione sul commento in merito alle decisioni di gruppo. Francamente credo che lunedì si debba prendere in considerazione l'idea di spendere 15 minuti per un ripasso generale di come funziona il progetto. Tutti insieme. Tu Diego che sei quello con le idee più chiare fai un riassunto generela... noi ti ascoltiamo senza obbiezioni e poi analiziamo insieme i punti "caldi". Basta iterazioni e perdite di tempo. Lunedì ci chiariamo una volta per tutte e definiamo quelle linee guida ancora dubbiose! Che ne pensi?

**Comment by diegoberaldin** [comment]
Parte di quel che è successo era inevitabile e quasi auspicabile, parte invece non è accaduta come sarebbe dovuto. Il fatto che attualmente ci capisca qualcosa solo una persona in tutto il gruppo, ad esempio, è sintomo che non si è lavorato nel modo giusto. Mea culpa...

Io sono disposto a fare un _briefing_ lunedì riassumendo il punto della situazione, spiegando cos'è cambiato e stabilendo la strada da seguire a grandi linee per il futuro, però chiederei a **tutti gli interessati**:
- di dare un'occhiata alla ST per sapere di cosa si parla;
-  di essere più "aperti mentalmente" e collaborativi anche se la direzione in cui si sono orientate le cose non è quella che ci piacerebbe.

Io, ad esempio, ero per una rubrica Mene-like pura senza limitazioni sul livello di ramificazioni, gruppi nella _blacklist_, ecc. ecc. ma guardando le cose da un altro punto di vista mi sono accorto che forse stavamo facendo una cosa troppo contorta e farraginosa.

PS: Se dalle iterazioni guadagniamo qualcosa, visto che ormai abbiamo sforato coi tempi, tanto vale farlo!

**Comment by Rizzi-Andrea** [comment]
Ok BOSS. Oggi festeggio il comple del Bro, ma entro sera mi ridò una letta generale... domani mi spieghi le cose che non capisco, e insieme mettiamo il punto esclamativo su questa storia! Aggiungo inoltre le mie più sentite scuse per il mio comportamento... sconfortato dai continui mutamenti ho praticamente abbandonato la ST sulle tue spalle... affinché ciò non riaccada ti esorto a incazzarti come una iena qualora rivedessi un mio allontanamento! ;) Per minacciarmi ricordati che ho paura del fuoco, delle affettatrici e dei film horror koreani!

**Comment by diegoberaldin** [comment]
Corretto il testo, rimane da correggere il diagramma!

**Comment by B1uRay** [comment]
corretto da elena. manca da esportare. chiudo.
