### ISSUE TITLE
[ST] controllare aggiornamento alla nuova versione

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#124]
Ho finito di riorganizzare la ST ma ho bisogno che un progettista dia un'occhiata al _sorgente_ aiutandomi a risolvere i vari `TODO` ivi disseminati. Se nessuno può nel weekend, ci metteremo io e qualche progettista **paziente** a rileggere il tutto lunedì. Finché non vedo che nessuno prende in carico l'issue, mi riservo la possibilità di apportare ulteriori interventi correttivi al documento.

**Comment by Rizzi-Andrea** [comment]
Oggi possiamo farlo noi due dopo Tec Web ^_^

**Comment by diegoberaldin** [comment]
Te la appioppo per ora, in parte hai fatto in parte farai domani! E speriamo di finire perché urge andare avanti, non possiamo stare fermi qui in eterno!
p.s. Spero che il "punto della situazione" sia servito a qualcosa oggi...

**Comment by Rizzi-Andrea** [comment]
Parte del server verificata/corretta e committata! Stasera procederò alla verifica di presenter e view!

**Comment by diegoberaldin** [comment]
Ok, grazie! Scusa i tempi biblici...

**Comment by Rizzi-Andrea** [comment]
Nessun problema! Per il momento il presenter mi sembra chiaro... o meglio... è attinente con quanto abbiamo deciso (va da se che ho un po' paura sul come realizzeremo poi (davvero) le cose che abbiamo scritto) ... (nn credo sarà cosi facile -.-'). Ottima la parte di presentazione dell'architettura presenter... Buone le descrizioni delle componenti, anche se ammetto di essermi un po' perso nel mare di nomi usati! Ricontrollando al dettaglio non mi sembra siano rimasti nomi obsoleti.

**Comment by diegoberaldin** [comment]
Ok, superare una verifica di Rizzi il Magnifico non è cosa da poco! Domani ad ogni modo mi spieghi meglio dove ti sei perso, non vorrei fosse sintomo di qualcosa che non va, forse il

> mi sembra chiaro... o meglio...

nasconde il fatto che non è molto chiaro o, peggio, che c'è qualche errore. Grazie in ogni caso per la pazienza!

**Comment by Rizzi-Andrea** [comment]
no no fidati... di per se è scritto bene... il punto è che sono stanco morto e  nel passare da gestione comunicazione a gestione conessione, con i vari nomi che sono stati aggiunti e modificati, ho finito con il perdermi nel limbo dei nomi XD. Ma cmq relax ;) è un buon lavoro... intanto continuo nell'opera di verifica!

**Comment by Rizzi-Andrea** [comment]
Ah ecco una cosa... dobbiamo chiarirci meglio su questo Client... mi pare che la cosa non sia chiarissima... sia per come è riportata su gestione comunicazione prima, che sulla descrizione della classe stessa dopo.

**Comment by diegoberaldin** [comment]
Ci sono da sistemare #127, #134 e #135 che riguardano, tra l'altro, anche questo. Se hai illuminazioni cambia pure il documento (ma tieni conto che ho trasferito qualche commit in remoto stasera).
