### ISSUE TITLE
[SynthesisRequirementManager] definire e aggiungere nuovi requisiti 

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#126]
NOTA: inserirli prima in un txt da caricare su DropBox per Her Stefano (alias B1uRay -.-')

**Comment by Rizzi-Andrea** [comment]
Dopo un analisi sul lavoro di Her Stefano, mi sento di supportare le seguenti modifiche:

 modificare come segue:

 RUFO6.1.0 stabilire una comunicazione audio con un utente in linea
 RUFO6.2.0 stabilire una comunicazione audio e video con un utente in linea

 aggiungere

 RUFO6.3.0 mantenere la comunicazione audio fino a che uno dei due utenti non la chiude, o non cade la linea da uno dei due nodi (evento non gestibile)

 RUFO6.4.0 mantenere la comunicazione audio e video fino a che uno dei due utenti non la chiude, o non cade la linea da uno dei due nodi (evento non gestibile)

 modificare come segue

 RUFF6.2.2 Stabilire una comunicazione audio e video con un utente presente nella rubrica

 RUFF15.5.0 Possibilità di cambiare lo stato del messaggio da "non ascoltato" a "ascoltato"

 modificare come segue

 RUFF16.0.0 Fornire la possibilità di cambiare lo stato utente

 aggiungere

 RUFF16.1.0 Fornire la possibilità di impostare "disponibile" come stato utente

 RUFF16.2.0 Fornire la possibilità di impostare "non disponibile" come stato utente

 RUFF20.1.0, RUFF20.2.0 sostituire condividere con condivisione 

 RSDO11.4.0 il server sarà coinvolto solo per avviare la comunicazione

Richiedo un parere esterno da parte del BOSS @diegoberaldin ^_^

**Comment by diegoberaldin** [comment]
Approvo tutte le modifiche proposte da @B1uRay e recepite da @Rizzi-Andrea. :+1: 

Chiedo inoltre:
- è stato cambiato anche 19.0.0 togliendo il termine "possibilità"? Non lo vedo come strettamente necessario (si verifica allo stesso modo) ma forse è il caso di toglierla visto che ci ha "deprecato" tutti gli UC dove compariva...
- è stata sistemata la fonte di RSDO22.0.0 (che probabilmente era "Capitolato d'appalto")?
- è stato modificato RSDD2.2.0 togliendo il "completamento" che non si sa bene a cosa si riferisca?

**Comment by Rizzi-Andrea** [comment]
Ci sono ancora 3 punti evidenziati da Stefano che dovrò chiarire domani con lui. Quindi quanto hai visto non sono tutte e sole le modifiche da fare (sorry... forse avrei dovuto dirlo prima). In merito alle tue domande:

1) Si è vero... ho omesso di riportarla sul commento iniziale... mea culpa :(

2) No non ancora... ho segnato che è da fare!

3) No... era uno dei punti che volevo capire con Stefano, ma credo di esserci arrivato

In sintesi chiedo scusa per la confusione... oggi mi sento un po' tardo... cioè... più del solito -.-'

**Comment by diegoberaldin** [comment]
¡No te preocupes tío, no pasa nada!
Direi che quel che ho visto sono tutte modifiche da fare, ma non sono le sole... cioè spero che quantomeno tutto quel che sta scritto lì verrà cambiato, non che non ci sia alcuna correlazione fra le cose :smile:

**Comment by B1uRay** [comment]
Non ho capito bene quali siano i dubbi, in ogni caso domani sono disponibile ad ogni chiarimento. =)
No ghe se problemi! (Non sapendo lo spagnolo....xD)

**Comment by B1uRay** [comment]
risolti i dubbi relativi. Appena verranno caricati (ed esportati) dal db sistemo i test di conseguenza.

**Comment by Rizzi-Andrea** [comment]
Notifica cambiamento stato DB... modificati i seguenti requisiti!

 RUFO6.1.0 stabilire una comunicazione audio con un utente in linea
 RUFO6.2.0 stabilire una comunicazione audio e video con un utente in linea
 RUFF6.2.2 Stabilire una comunicazione audio e video con un utente presente nella rubrica 
 RUFF15.5.0 Possibilità di cambiare lo stato del messaggio da "non ascoltato" a "ascoltato" 
 RUFF19.0.0 presenza di uno storico delle chiamate 
 RUFF16.0.0 Fornire la possibilità di cambiare lo stato utente
 RUFF20.1.0, RUFF20.2.0 sostituire condividere con condivisione  
 RSDO11.4.0 il server sarà coinvolto solo per avviare la comunicazione 
 RSDD2.2.0 inserimento dei dati facoltativi riferiti all'anagrafica

**Comment by Rizzi-Andrea** [comment]
Notifica cambiamento stato DB... aggiunta fonte mancante per il requisito #22

**Comment by Rizzi-Andrea** [comment]
Notiica cambiamento stato DB... aggiunti requisiti

 RUFF16.1.0 Fornire la possibilità di impostare "disponibile" come stato utente
 RUFF16.2.0 Fornire la possibilità di impostare "non disponibile" come stato utente
 RUFO6.3.0 mantenere la comunicazione audio fino a che uno dei due utenti non la chiude, o non cade la linea da uno dei due nodi (evento non gestibile)
 RUFO6.4.0 mantenere la comunicazione audio e video fino a che uno dei due utenti non la chiude, o non cade la linea da uno dei due nodi (evento non gestibile)

**Comment by Rizzi-Andrea** [comment]
Tutte le modifiche e le aggiunte prestabilite sono state apportate. Considero l'issues chiuso. Avviasatemi se ritenete ci siano errori o considerazioni in merito!
