### ISSUE TITLE
[SynthesisRequirementManager] aggiornare tabelle relative ai componenti e alle classi

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#128]
In particolare, si tratta delle tabelle:
- Componenti
- ComponentiClassi
- ComponentiPatterns
- RequisitiComponenti
- Classi

**Comment by Rizzi-Andrea** [comment]
BLAAAAAAAAAAAAAAAAAAAAAAA :P è un lavoro che odio... ma immagino sia il caso che lo prenda io in consegna. Tuttavia vorrei aspettare a farlo... cambiare le componenti per sentirmi dire "hei Rizzi... abbiamo fatto altre iterazioni, devi tornare sul DB" potrebbe far riemergere lo Smeagol che è in me XD

**Comment by diegoberaldin** [comment]
Non è stato fatto sinora perché non era ancora ben fissato il tutto, in teoria dopo il tuo lavoro di oggi dovrebbe essersi stabilizzata la situazione ma consiglio di aspettare ancora! In ogni caso il gran capo sei tu ora quindi hai la facoltà (e il dovere, se sei richiesto altrove) di delegare l'attività a qualcun altro...

**Comment by Rizzi-Andrea** [comment]
No no ;) meglio se me ne occupo io... ho lavorato già un po' con il DB, quindi ormai sono di casa ... per cosi dire XD

**Comment by diegoberaldin** [comment]
Si è deciso che la facciamo a mano questa? Se sì @Rizzi-Andrea chiudi pure (magari mettendo etichetta WONTFIX)!
