### ISSUE TITLE
[PdQ] verificare sezione "Tecniche, metodi e metriche"

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#129]
verificare se le aggiunte e le modifiche fatte da @B1uRay corrispondono alle attese

**Comment by diegoberaldin** [comment]
Ho fatto una verifica molto "blanda" come si può vedere [nella pagina del commit](https://github.com/SoftwareSynthesis/SoftwareEngineeringProject/commit/5c90dffbbebd2fb5228716cc98d78d188ab1b2d8).

In ogni caso, mi sentirei di dirti le seguenti osservazioni:
- io sposterei quel che c'è scritto in 5.3.1 "Metriche per il progetto" nella sezione 5.3 in quanto mi sembra che si riferisca alle metriche in generale;
- nella sezione "Metriche per il progetto" mi affiderei a quello che dice [Wikipedia](http://it.wikipedia.org/wiki/Metriche_di_progetto) perché ho visto che **non saremmo gli unici** a prendere spunto, anche pesantemente, da quella pagina.

Che ne pensi? Se mi dai la tua conferma posso farlo io domani! :smile_cat:

**Comment by B1uRay** [comment]
Autorizzo autorizzo, infatti come ti dicevo oggi c'erano sicuramente dettagli da sistemare. Comunque al massimo ne parliamo domani senza problemi! ;-)

**Comment by diegoberaldin** [comment]
@B1uRay ho fatto. Chiedo ora a te verifica! :)

**Comment by B1uRay** [comment]
controllato, mi sembra tutto corretto e coerente. Sicuramente chi farà la verifica finale sul documento valuterà tutto l'insieme. Chiudo. ;-)
