### ISSUE TITLE
[ST] ultima verifica diagrammi attività

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#130]
Ecco le due cavolate che ho visto:
- in _Comunicazione audio_ nell'ultimo ramo del fork manca una freccina che entra nel merge
- in _Gestione account personale_ la freccia che entra in "modifica immagine associata" sormonta l'azione "modifica cognome"

Banalità/Conflitto di norme:
- i normi dei file con l'underscore si era scelto di evitarli e di usare il camelCase ma, nonostante tutto, non davano problemi perché LaTeX non si incazzava particolarmente;
- ora che sono stati cambiati, occorre cambiare il nome del file in `\includegraphics{}` nel documento.

È una boiata ma si poteva evitarlo. Ho cambiato i nomi io cmq (ora il documento non compila finché non ci sono le immagini giuste, domani le mettiamo subito!)

**Comment by B1uRay** [comment]
ok, domani mattina (pardon, pomeriggio) sistemo al volo e ri-esporto. ;-)

**Comment by B1uRay** [comment]
sistemati ed esportati. Scusa ma non capisco dove sia stato usato la nomenclatura con l'underscore, nella cartella "immagini diagrammi attività 2.0" sono rinominati tutti con il camelCase...sicuro di non aver confuso le cartelle? :-)

EDIT: risolto. chiudo.
