### ISSUE TITLE
[ST] chiarire relazioni per classi TO che modellano associazioni

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#131]
In particolare, come devono essere le frecce di composizione fra `UserData` e `CallList` e `Call`? E, inoltre, mi pare di capire che dobbiamo togliere `MessageBox`.

**Comment by diegoberaldin** [comment]
@meneghinello-andrea tu che hai capito come funziona Hibernate puoi certamente aiutare..

**Comment by diegoberaldin** [comment]
Esito della discussione:
- togliere `IMessageBox` e `MessageBox` da Gestione segreteria
- `Message` dovrebbe avere due riferimenti a `IUserData`
- `AddressBook` deve avere due riferimenti a `IUserData`
- `UserData` non deve avere riferimenti a `IAddressBook`
- `Group` non deve avere riferimenti a `IUserData`
- `CallList` e `ICallList` non esistono più

Sono da rivedere sia le descrizioni che i diagrammi (per @MissEle)

**Comment by diegoberaldin** [comment]
Io la lascerei aperta perché ci sono 3 diagrammi da correggere alla luce di quanto scritto sopra.

Inoltre, nella descrizione del componente "Gestione chiamate" compare nella lista delle classi utilizzate `JSCallList` ma non è menzionata nella descrizione generale del componente.

**Comment by Rizzi-Andrea** [comment]
Ecco una cosa che ti volevo chiedere... ma è giusto che in una componente del server compaiano delle classi del presenter? Ho capito l'utilizzo di JSCallList, ma io la citerei solo lato presenter, visto che è li che viene usata concretamente.

**Comment by diegoberaldin** [comment]
A suo tempo sembrava sensato perché `Call`, `UserData` e `Message` dovevano provvedere un'operazione `toJS(): String` che li trasformasse in `JSCall`, `JSUserData` e `JSMessage`... ma ora non sembra più così logico anche perché si trasformano soltanto in stringhe!

Uccidiamoli tutti  pure quelli, però allora li uccidiamo tutti e cioè
- via `JSCallList` e `JSCall` da "Gestione chiamate"
- via `JSMessage` e `JSMessageBox` da "Gestione segreteria"
- via `JSUserData`, `JSGroup`,  `JSAddressBook` da "Gestione rubrica"

In ogni caso non è strano che una classe compaia in più componenti, cioè magari è sbagliato ma da noi questa cosa si verifica in più casi :smile:  Infatti in SynthesisRequirementManager l'associazione fra componenti e classi è N:M...

**Comment by Rizzi-Andrea** [comment]
one moment... sono comunque necessarie lato client... giusto? Tu dici di eliminarle dalla zona del server e stop... vero?

**Comment by diegoberaldin** [comment]
Sì, dal server.. cioè dalle descrizioni dei componenti citati sopra (che sono tutti componenti del server) e dagli elenchi delle classi utilizzate nei componenti di sopra...

No no per carità teniamole sotto in "Rappresentazione dati"!
