### ISSUE TITLE
[PdQ] correggere definizione di "complessità ciclomatica" 

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#132]
Basarsi sulle slide di Tullio e su quanto detto nella lezione del 20/02

**Comment by B1uRay** [comment]
Sistemato. Da verificare e chiudere.

**Comment by diegoberaldin** [comment]
Verificato! Non ho cambiato molto se non:
- mettere gli ambienti matematici invece dei corsivi
- rendere la definizione un'unica frase per poter usare il `;` alla fine come per le altre metriche.

Grazie per aver fatto al posto mio questa cosa!
