### ISSUE TITLE
[ST] architettura del database

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#133]
È stata definita la sezione della progettazione concettuale e logica del database con la rubrica in modalità Tres like. È necessaria una verifica della sezione

**Comment by Rizzi-Andrea** [comment]
La eseguo subito! ^_^

**Comment by Rizzi-Andrea** [comment]
Allora... nella visione d'insieme è tutto corretto. Il db rispetta la struttura prestabilita. Vorrei però sottolineare 2 punti:

1) nella tabella AddressBook della modellazione logica,  il campo Owner non dovrebbe avere un vincolo di chiave esterna con la tabella UserData?

2) Non capisco perchè nella modellazione concettuale il tipo di alcuni dati è UserData. Effettivamente è vero che "concettualmente" in molte tabelle c'è un campo che fa riferimento all'utente, ma il tipo non dovrebbe cmq essere quello della chiave primaria di UserData? è fondamentalmente corretto porre come tipo un intera entità?

**Comment by diegoberaldin** [comment]
Riguardo 2) a occhio sembrerebbe trattarsi di un errore. Tra l'altro - essendo chiavi esterne - sarebbe anche possibile non rappresentarle affatto nel modello concettuale, così come ad esempio non è stata inserita alcun campo in AddressBooks che punta a Groups.

**Comment by Rizzi-Andrea** [comment]
Ok Diego... aspettiamo cmq di saperne di più dal Mene.

**Comment by meneghinello-andrea** [comment]
Tolti dalle tabelle i campi dati con tipo 'UserData' e definita nel modo più preciso l'associazione tra UserData e Messages, si tratta infatti di due associazioni uno a molti. Modificato anche lo schema del database
