### ISSUE TITLE
Sistemare dati SynthesisRequirementManager

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#14]
Da correggere i dati del database e aggiornarli all'ultima versione

**Comment by RikyTres** [comment]
Completato al 50%
Quando saranno completate le classi potremo sistemarle nel DB.

**Comment by RikyTres** [comment]
Completato al 90%
Mancano le classi grafiche.

**Comment by RikyTres** [comment]
Le ultime Classi le inserisci Rizzi

**Comment by diegoberaldin** [comment]
Corretto con inserimento delle classi grafiche! E controllata associazione Componenti-Design Pattern..
