### ISSUE TITLE
[ST] verificare nella ST che il nome MessageBound sia riportato correttamente.

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#145]
verificare che la classe delle librerie Apache sia effttivamente quella e fornire il nome completo tramite il package che la contiene.

**Comment by diegoberaldin** [comment]
A me risulta che il nome completamente qualificato della classe che cerchi sia `org.apache.catalina.websocket.MessageInbound`
 come ho visto [nella documentazione di TomCat](http://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/websocket/MessageInbound.html)

**Comment by Rizzi-Andrea** [comment]
OTTIMO!
