### ISSUE TITLE
[ST] Verificare modifiche al sistema di comunicazione

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#146]
iter di verifica:
1) controllare l'introduzione all'architettura server
2) controllare l'introduzione all'architettura presenter
3) controllare componente gestione connessione (Server)
4) controllare package connection (server)
5) controllare componente kernel (presenter)
6) controllare componente gestione remota (presenter)
7) controllare package kernel (presenter)
8) controllare che sia stato eliminato il nome webRTCInfo
9) controllare che sia stato eliminato il nome Iclient

**Comment by diegoberaldin** [comment]
Fatto, trovi qui il risultato: e213f6fa2e35c4e5c18cad0f70129c11a306cbfe e se vuoi lasciarmi commenti sulla pagina del commit fa' pure (si possono mettere riga per riga)! Scusa se ci ho messo tempo ma la verifica di queste cose deve essere puntigliosa! :)

Esito della verifica: **sei un ottimo equilibrista**! Io non avrei saputo fare di meglio e, per la prima volta, leggendo il nostro sistema di comunicazione ho la sensazione che possa funzionare per davvero! Incredibile ma vero! Siete stati bravissimi tu e @marcoskivo, se avessi scritto io quel pezzo si sarebbe capito da ogni virgola che non avevo idea né di come funzionasse né dell'eventualità che potesse un giorno funzionare.

Attenzione a certi erroretti che rendono più ostico (e meno concentrato sul contenuto) chi rilegge:
- tutti i nomi dei pattern sono stati scritti in maiuscolo, quindi anche «Adapter»
- il termine «pattern» va in _corsivo_ perché è in inglese (c'erano errori tuoi e anche miei di questo tipo)
- «settare» è bandito dal nostro dizionario
- «istanza» è un sostantivo femminile, quindi si dice «un'istanza» e non «un istanza»
- «WebRTC» abbiamo deciso di usarlo con la maiuscola, in più è un termine del glossario e quindi la prima occorrenza deve essere sottolineata, ho anche tolto «le WebRTC» (sottintendiamo librerie) o «il WebRTC»
- «communication» e «channel» (e tutte loro declinazioni) anche se si dicono con una «m» e una «n» rispettivamente si scrivono con due.

Se sei soddisfatto dei cambiamenti chiudi pure l'issue!

**Comment by Rizzi-Andrea** [comment]
Ho controllato la correzione. Si si :( azzarola... effettivamente avevo qualche dubbio su alcuni termini inseriti, compreso adapter. Avrei dovuto controllare meglio le norme. Prendo cmq nota dei 6 punti da te elencati al fine di non ripeterli. Non preoccuparti per le tempistiche, sei stato anche troppo bravo ;)
