### ISSUE TITLE
[ST] descrizione pattern Factory Method

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#150]
Nella descrizione dei componenti in cui è implementato il pattern si citano CS02 e CS07.

Ebbene, in CS07 non è proprio più il caso di nominarlo anche perché il pattern richiede che ci sia non solo un metodo con tipo di ritorno polimorfo, ma che questo metodo sia l'implementazione di un'operazione astratta contenuta in un'interfaccia. In CS07 ora questo non è più vero.

Per quanto riguarda CS02, invece, si cita ancora `connection.IConnection` che invece è stato sostituito da `connection.IChannel`!

**Comment by diegoberaldin** [comment]
@Rizzi-Andrea mi autorizzi a risolvere questi problemi?

**Comment by Rizzi-Andrea** [comment]
OK Diego ;) hai il via libera
