### ISSUE TITLE
[ST] diagrammi e descrizioni dei pattern

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#152]
Ci è stato contestato il fatto che abbiamo messo quasi ovunque diagrammi UML senza descrizione.

Per ovviare a questo problema nella sezione 9 di ST (descrizioni dei design pattern), proporrei: invece di mettere una descrizione per ogni diagramma e poi spiegare separatamente tutti i componenti che lo implementano, mettiamo direttamente il diagramma assieme alla descrizione del componente che lo implementa.

Tanto oramai i diagrammi sono specifici quindi la descrizione del componente **è** la descrizione del diagramma in effetti. Questo risolve anche il problema di Singleton, dato che ne abbiamo tre... :)

**Comment by diegoberaldin** [comment]
Al solito questo richiede di cambiare la sezione 7.2 delle NdP.. perché visto che siamo italiani facciamo le norme sulla base di quello che ci fa comodo!

Scherzi a parte le norme dicevano "si riporterà lo schema UML rappresentante un implementazione generica del design pattern in esame" ma questa cosa Cardin ce l'ha contestata!

PS. Nelle norme "design pattern" va in corsivo e "un'implementazione" si scrive con l'apostrofo!

**Comment by Rizzi-Andrea** [comment]
Dovrei aver assegnato a Stefano il compito di modificare le norme. Faccio un controllo e nel caso chiudo l'issues

**Comment by Rizzi-Andrea** [comment]
Ottimo. Stefano ha corretto il punto alla perfezione. Considero l'issues chiuso!
