### ISSUE TITLE
[ALL] conflitto di interessi

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#160]
Aggiornare frontespizio mostrando solo gli ultimi redattori del documento, la questione dei colori non dovrà più essere utilizzata. Non utilizzare più la macro `\currentauthor` che sarà presto tolta dal preambolo dei documenti.

Rivedere anche:
- NdP sezione 4.3 "Impostazioni di base di un documento"
- PdP sezione 5.2 "Rotazione ruoli"

Idealmente chi fa questa issue dovrebbe anche fare la #110.

**Comment by diegoberaldin** [comment]
@B1uRay visto che hai le "mani in pasta" in PdP e NdP potresti farlo tu per favore?

**Comment by B1uRay** [comment]
sulle NdP ho sistemato (era semplicemente una riga da cambiare) mentre la sezione 5.2 del PdP non mi sembra particolarmente sbagliata, anzi. 
Eventualmente se avete modifiche mirate da segnalare fatelo pure ma ripeto, a me sembra discretamente corretto quanto scritto. :-)
