### ISSUE TITLE
[ST] dovremmo avere anche ICallListDAO dato che CallList è un transfer object?

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#162]

**Comment by diegoberaldin** [comment]
ATTENZIONE: questo ha un impatto a cascata:
- sulla descrizione del componente CS01 - Gestione database
- sulla descrizione delle classi del package `server.dao`
- sul diagramma del componente CS01 - Gestione database
- sul diagramma del server generale
- sul diagramma del design pattern DAO

**Comment by meneghinello-andrea** [comment]
Secondo me non serve tale componente poiché tu dovrai lavorare con gli oggetti ai lati di una relazione molti a molti!!! Difficilmente dovrai inserire, modificare ecc.. un record della tabella per risolvere una relazione molti a molti. Ci dovranno pensare in modo trasparente gli oggetti che sono ai lati della relazione.
