### ISSUE TITLE
[DdP] scrivere HHHH sul capitolo degli standard

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#163]

**Comment by B1uRay** [comment]
Fatto, in tutti gli standard si rimanda alle norme di progetto (dove sono elencati tutti per filo e per segno) o al piano di qualifica (per gli strumenti, mancano solo quelli relativi ai test). 

Lascio aperto solo per un controllo veloce e per ricordare di controllare di conseguenza anche gli altri due documenti.

**Comment by Rizzi-Andrea** [comment]
Grazie Stefano... bel lavoro. Ora controllo!
