### ISSUE TITLE
[ST - Abstract must die - parte 1] Fuori uno! ^_^)/

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#165]
Eliminare prefisso MySQL dalle classi MySQLCallDAO, MySQLGroupDAO,
MySQLMessageDAO e MySQLUserDataDAO perché sono indipendenti dal DBMS;

**Comment by diegoberaldin** [comment]
Occorre quindi cambiare sia l'elenco delle classi presentato alla fine di CS01 che il nome delle classi e la descrizione di queste ultime alla fine della sezione relativa alla sotto-architettura server
