### ISSUE TITLE
 [ST] Dobbiamo comunque avere `call.ICallList` e `call.CallList`?

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#168]
Se con Hibernate è davvero tutto automatico dovremmo dimenticarci di avere anche la tabella CallLists e così come su `abook.IUserData` ci sarà un'operazione del tipo

```
  + getMessageBox(): List<IMessage>
```

a questo punto dovremmo anche poter avere qualcosa del tipo

```
+ getIncomingCalls(): List<ICall>
+ getOutcomingCalls(): List<ICall>
```

Questo ha un impatto, ovviamente, non solo sulla descrizione delle classi ma anche sui diagrammi.

**Comment by diegoberaldin** [comment]
Ricordo a tutti che, tra l'altro, la tabella  CallLists è piuttosto ostica in quanto ha quel vincolo tale per cui per ogni gruppo di ennuple aventi lo stesso ID_Call può essercene solo una che ha l'attributo Caller a `true`.

Ora, non per il cinismo che mi contraddistingue, ma già è una relazione molti-a-molti che in Hibernate sono le più rognose e in più ha questi  vincoli non banali... ho come la sensazione che sarà un fallimento!

Spero che quanto detto in #162 sia vero e cioè che ci si possa dimenticare dell'esistenza di quella tabella.

**Comment by meneghinello-andrea** [comment]
Per rispondere ad @Rizzi-Andrea che ha aperto questa issues non credo che ci saranno due getter separati (chiamate in ingresso e in uscita) ma molto probabilmente ce ne sarà uno solo che restituirà tutte le chiamate e poi con regole di business facciamo la separazione in base al valore (true oppure false) del attributo 'caller' nell'entità 'CallLists'
