### ISSUE TITLE
[ST - Abstract must die - parte 5] Tanto lavoro e niente svago fanno di Diego un bambino arrabbiato! XD

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#171]
- eliminare la descrizione di Abstract Factory dall'elenco dei design
  pattern utilizzati (e il relativo diagramma). Fatelo per Diego <3

**Comment by diegoberaldin** [comment]
Lo faccio io, io l'ho creato e io lo distruggo..

**Comment by Rizzi-Andrea** [comment]
Muahaha la vendetta è un piatto dolce eh? Cmq -bravo Diego! Ottimo lavoro! ;)
