### ISSUE TITLE
[ST] classe DAO per AddressBook?

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#172]
Abbiamo `abook.IAddressBook` e `abook.AddressBook` che però hanno una corrispondenza diretta con un'entità del database e non è per un'associazione molti-a-molti. Dovremmo quindi avere una classe `dao.AddressBookDAO` o mi sbaglio?

Inoltre in "Rappresentazione delle associazioni" è rimasto citato il tipo di dato UserData.

**Comment by Rizzi-Andrea** [comment]
Io personalmente non mi sento di dare una risposta certa. Per essere sicuri sul da farsi chiederei al creatore del sistema DAO @meneghinello-andrea.

**Comment by meneghinello-andrea** [comment]
Si dovremmo avere anche l'interfaccia IAddressBookDAO e AddressBook che è un implementazione di IAddressBook. Questo perché l'entità nel database chiamata AddressBooks non è più vista come una entità che risolve una relazione molti a molti ma bensi un'entità con relazioni uno a molti come rappresentato dall'entità Messages e UserData
