### ISSUE TITLE
[ST - A Scanner Darkly - parte 3] Resa dei conti nella terra dei pattern selvaggi!

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#175]
Sulla base di quanto spiegato da Riccardin:
- rivedere il diagramma di "CS03 - Gestione rubrica" che deve
  rispecchiare il pattern Observer.

**Comment by diegoberaldin** [comment]
Rivista descrizione delle classi e del componente.
