### ISSUE TITLE
[Observer] Pattern observer per la parte server

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#176]
Alla luce della discussione che avete avuto con Riccardin venerdì scorso riguardo al design pattern Observer per la gestione degli stati degli utenti ho pensato di proporre la seguente soluzione al problema:
- Definizione della classe ''StatusChangedEvent'' classe che estende la classe ''java.util.EventObject''. 
  Tale classe possiede come campi membro i seguenti riferimenti:
  - user: riferimento allo IUserData che ha avuto un cambiamento di stato;
  - older: riferimento allo IState precedente;
  - newer: riferimento allo IState. attuale.

Possiede inoltre dei getter per poter visualizzare tali informazioni che possono essere inizializzate solo nel costruttore.
- Definizione dell'interfaccia ''IUserDataListener'' che estende l'interfaccia ''java.util.EventListener''.

Tale interfaccia possiede la firma del metodo:
- statusChanged(StatusEventChanged event);

Tale metodo possiede il codice per la gestione del cambiamento di stato
- Infine il Transfer Object UserData dovrà implementare l'interfaccia ''IUserDataListener'' poiché un utente dovrà essere osservatore del cambio di stati altrui. Oltre ai campi membro per mappare gli attributi dell'entità UserData dovrà contenere come campo membro:
  - javax.swing.event.EventListenerList che è una lista di ascoltatori di eventi.

Dovrà inoltre possedere dei metodi pubblici per poter registrare e togliere un altro UserData come ascoltatore per il cambio di stato per l'utente attuale. Tali metodi avranno la seguente implementazione:

```
public void addUserDataListener(IUserDataListener listener)
{
     eventListener.add(listener.class, listener);
}

public void removeUserDataListener(IUserDataListener listener)
{
     eventListener.remove(listener.class, listener);
}
```

Avrà inoltre il metodo, da richiamare quando lo stato di utente cambia, per il lancio dell'evento tale metodo dovrà essere il seguente:

```
protected void fireStatusChanged(IUserData user, IStatus older, IStatus newer)
{
     StatusChanged event = new StatusChanged(user, older, newer);
     Object[] listenerArray = eventListener.getListenerList();
     for(int i = listenerArray.length - 2; i >= 0; i -= 2)
     {
          if(listenerArray[i] == IUserDataListener.class)
          {
               ((IUserDataListener)listenerArray)statusChanged(event);
          }
     }
}
```

Cosa ne pensi @diegoberaldin @Rizzi-Andrea

**Comment by Rizzi-Andrea** [comment]
Guarda Mene... onestissimamente non credo di aver capito totalmente il sistema... anche se me l'hai spiegato a voce... e questo mi fa sentire abbastanza stupido.... Tuttavia se sei davvero convinto del sistema (soprattuto in virtù di quello che ti ho riassunto dul server) allora ok... hai il via libera... Al più dopo giudicheremo la soluzione in confronto con la risposta del Cardin...

**Comment by meneghinello-andrea** [comment]
Con il metodo sopra esposto abbiamo che uno UserData può diventare osservatore sul cambio di stato di altri UserData, agganciandosi con il metodo `addUserDataListener`. Quando uno UserData cambia stato, ossia si esegue un istruzione del tipo`userData.setState(new StateOffline());` all'interno di quel set si dovrà effettuare una chiamata al metodo `fireStatusChanged(....)` cosi facendo abbiamo lanciato un evento di cambio stato che sarà gestito dagli UserData che sono osservatori attraverso il metodo `statusChanged(....)`.

**Comment by diegoberaldin** [comment]
Ok, credo di aver capito anche se onestamente trovo leggermente fuorviante avere `void statusChanged(StatusChangedEvent s)` come identificatore del metodo dell'interfaccia del Listener, forse `onStatusChanged(StatusChangedEvent s)` che rende più l'idea..

Proverei ad azzardare che la maggiore fonte di confusione per @Rizzi-Andrea  è stato che il nome della classe sottotipo di `EventObject` è stata prima dichiarata come `StatusChangedEvent`, poi nelle segnature dei metodi è diventata `StatusEventChanged` e infine nella definizione dei metodi è diventata penso erroneamente `StatusChanged` che peraltro era anche il nome (con la "s" minuscola) del metodo...

Comunque, due osservazioni:
- non sono sicuro di aver capito come si scorre la lista di listener, perché un elemeno sì e un elemento no (ma ho paura che sia perché per ogni Listener c'è anche il suo oggetto .class... anche se spero di sbagliarmi) :)
- non metto in dubbio che la cosa funzioni (tra l'altro `java.util.Observer` e `java.util.Observable` hanno un ruolo molto simile, però l'idea di sottoclassare `EventObject` mi piace molto assai!!!) solo che è difficile far vedere il _pattern_ Observer, che c'è ma Java ce lo nasconde con la reflection... Se adottiamo questa soluzione lo toglierei dall'elenco dei _pattern_...

**Comment by meneghinello-andrea** [comment]
Concordo con te diego per la firma del metodo....e gli errori sono errori di distrazione. Chiedo perdono!!!! ;)

Risposta alla prima osservazione: Li scorri a due a due perché c'è l'oggetto .class. Siccome il vettore da scorrere è unico e può contenere diversi tipi di listener il .class server per fare il cast nel metodo `fireStatusChanged(...)`

**Comment by diegoberaldin** [comment]
Sì, è potente questa cosa, permette di avere listener anche eterogenei registrati su di uno stesso soggetto (anche se non capisco perché non era sufficiente un semplice tipo interfaccia per risolvere il problema, es. bastava usare `EventListener` in add e remove, ma domani casomai mi spieghi meglio).

**Comment by meneghinello-andrea** [comment]
Allora si utilizzano le interfaccie Observer e la classe Observable per risolvere il problema!!!
