### ISSUE TITLE
[ST] rivedere descrizione associazione UserData-AddressBooks N:1

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#177]
Quel che c'è scritto nella descrizione

> rappresenta il legame che intercorre tra una rubrica e gli utenti presenti in essa

farebbe sembrare che sia "molti" nel lato di UserData. Questo ha senso, ma non è quel che modelliamo nel database tant'è che non c'è una chiave esterna da UserData a AddressBooks ma viceversa.

Il nome "AddressBooks" per quella tabella porta fuori strada solo me? Anche coi gruppi sembrerebbe che un addressbook dovesse avere molti gruppi e invece è il contrario abbiamo che molti addressbook sono in un gruppo (con la chiave esterna in AddressBooks) perché gli "addressbook" sono in realtà i contatti e non le rubriche...

**Comment by Rizzi-Andrea** [comment]
In merito al nome no... vai tranquillo... anche io ci stavo per cascare. È un nomer forviante, ma alla fine ho deciso di mantenerlo, per non dover poi diventare deficienti a cambiare nome. Cmq assegno l'issues al Mene... e vediamo che dice.

**Comment by diegoberaldin** [comment]
Se teniamo il nome (mille volte mi sa che ci abbiamo pensato e mille volte abbiamo deciso di tenerlo per non impazzire) allora io renderei ancor più fuffa-style la descrizione dell'associazione in modo che il cervello del lettore si spenga all'istante e non faccia caso a dove stanno le chiavi e perché..

E se no sara el ticket e mì gheła moło de rompare i maroni...

**Comment by meneghinello-andrea** [comment]
Il nome è proprio fuorviante...avremmo dovuto cambiare quando abbiamo adottato la rubrica Tres-like. Non ho capito la prima obiezione di diego in merito a quanto scritto nella sezione database della ST

**Comment by Rizzi-Andrea** [comment]
Verificato. Tutto corretto!
