### ISSUE TITLE
[NdP] php in "Norme sul codice JavaScript"

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#178]
> In fase di codifica della parte JavaScript i programmatori dovranno fare in modo che il codice prodotto sia mantenuto in file con estensione `.js` separati rispetto alla parte _php_ e _html_...

Non capisco cosa c'entri PHP...

**Comment by B1uRay** [comment]
probabilmente un lapsus o un rimasuglio di "suggerimenti"...xD correggo

**Comment by B1uRay** [comment]
fatto ;)
