### ISSUE TITLE
[NdP] cartelle revisioni

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#179]
> È inoltre presente una cartella `Revisioni'', composta a sua volta da quattro sotto-cartelle (`RR'', `RP'',`RQ'', ``RA'') che conterranno i documenti formali consegnati alle quattro revisioni del progetto ed una cartella`pics` che conterrà tutte le immagine utilizzate nei documenti.

Questa cosa non ce l'abbiamo o, meglio, queste cartelle sono nell'innominabile Dropbox... come facciamo? Adeguiamo la norma alla realtà o adeguiamo la realtà alla norma?

Se questa cosa giunge alle orecchie di colui-che-tutto-sa-e-tutto-sente posso essere colpito da un fulmine..

**Comment by B1uRay** [comment]
tralasciando il fulmine (tanto sono sicuro che ti ha già colpito...a meno che tu non sia vicino a Schivo xD) non penso cambi molto la cosa...su Dropbox le cartelle divise giustamente ci sono, e in generale una volta completati i DOC per le relative revisioni facciamo riferimento proprio a quella. Su git non c'è (penso) per una questione di "sdoppiamento"...

Si può sempre spostarla nel repo comunque se vogliamo essere più intervenenti possibili alle norme...fortunatamente non è un problema così cruciale :-)

**Comment by diegoberaldin** [comment]
Risolto da Mene mettendo tutti i file qui su GitHub.. :-)
