### ISSUE TITLE
[ST] gestione stato

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#180]
Nella gerarchia di classi appartenente a "server.state" non dovrebbe esserci l'azione da intraprendere in base allo stato dello UserData? Cioè non dovrebbe esserci il metodo call(...) che esegue cose diverse in base allo stato?

**Comment by diegoberaldin** [comment]
Questione chiusa, rimuovendo brutalmente l'intero componente CS04 Gestione stato... :-(
