### ISSUE TITLE
Documentazione javadoc

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#181]
Nella descrizione della documentazione hai inserito anche l'opzione @override? Se no va aggiunta e serve per prendere, in automatico, una descrizione definita per un metodo di una interfaccia/superclasse e applicarla anche allo stesso metodo definito nella sottoclasse senza bisogno del copia/incolla. Se dovessi già averlo fatto chiudi pure la issues

**Comment by B1uRay** [comment]
appena arrivo a pd controllo...in ogni caso sistemo entro le 12 ;)

**Comment by meneghinello-andrea** [comment]
Thanks

**Comment by meneghinello-andrea** [comment]
Serve inoltre al compilatore per controllare il corretto uso di overloding e overriding

**Comment by B1uRay** [comment]
inserito con praticamente quanto hai riportato tu qui sopra...non ho trovato altre info dettagliate (ho fatto una ricerca veloce, ma confidavo che già la tua "descrizione" fosse corretta).

Chiudo.
