### ISSUE TITLE
AdressBooks: utenti della rubrica (?)

### ISSUE THREAD

**Issue by B1uRay** [SoftwareSynthesis/SoftwareEngineeringProject#182]
Lascio la Issues semplicemente per "lasciar segno" e discutere più formalmente della denominazione assegnata agli "utenti appartenenti alla rubrica di un utente".

Come affermavo, con effettivo riscontro anche nelle vostre risposte, il nome è decisamente fuorviante rispetto a quanto effettivamente implementato dalla classe. 
Tale definizione (pare) è nata da un'iterazione asfaltativa su una precedente versione del database, che ha lasciato questo "ricordino".

Ora, partendo dal presupposto che una eventuale modifica di tale nome sarebbe puramente a scopo di rendere più chiara la comprensione di tale classe e relativa implementazione (sia per noi, che per Cardin), si può valutare la possibilità di correggere questo dettaglio? Quanto "costerebbe" l'eventuale modifica?

**Comment by diegoberaldin** [comment]
Alla fine si è deciso di operare le seguenti trasformazioni:
- nella progettazione del database la tabella "AddressBooks" è diventata "AddressBookEntries"; 
- il transfer object abook.AddressBook è diventato abook.AddressBookEntry e la relativa interfaccia è diventata abook.IAddressBookEntry; 
- nella gestione del database la classe DAO è diventata dao.AddressBookEntryDAO. 

Questo dovrebbe essere sufficiente a risolvere tutti i problemi dovuti alla presenza di nomi fuorvianti. 

Grazie @B1uRay per la segnalazione, questi pareri provenienti da persone "esterne" servono molto a capire dove le cose scrocchiolano..

**Comment by B1uRay** [comment]
sempre disponibile, "odio" fare in guastafeste, ma spero siano tutte segnalazioni costruttive per evitarci magagne future ;-)
