### ISSUE TITLE
Modificare MyTalk db tabella AddressBooks

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#184]
Aggiornare la struttura della tabella AddressBooks come segue:
- porre campo blocked come default 0
- owner va posto come "null" e non "not null"

**Comment by diegoberaldin** [comment]
Premetto che avendo guardato alle 21.30 del 27/02 nel documento di ST quel campo è rimasto come non opzionale.

Qualcuno mi spiega perché dovrebbe invece esserlo? L'associazione UserData-AddressBookEntries era effettivamente segnata come parziale verso UserData nel modello concettuale, ma siccome non tornavano i conti con le tabelle sotto l'avevo messa totale in quel verso (e parziale nell'altro).

In ogni caso, ritengo che dovrebbe essere totale verso UserData e, di conseguenza, che Owner dovrebbe essere not null. Riapro e domani ne parliamo.

**Comment by diegoberaldin** [comment]
Owner -> not null
ID_group -> default null
