### ISSUE TITLE
[database] AddressBookEntries e blocco contatti

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#186]
Siamo coscienti del fatto che le 5-uple di questa tabella che si differenziano solo per l'attributo `ID_group` devono avere sempre valori consistenti per il campo `Blocked`?

A me sembra una progettazione un po' scricchiolante, comunque il vincolo dovrebbe essere segnalato in ST e si dovrebbe cercare di mantenerlo nella programmazione/definizione di prodotto.

In alternativa si potrebbe pensare di cambiare la struttura del db.

**Comment by Rizzi-Andrea** [comment]
Parlando con Mene si è deciso di risolvere il problema tramite l'utilizzo di trigger!

**Comment by diegoberaldin** [comment]
Trigger?????! WTF???!
