### ISSUE TITLE
Gestire MVP nei tracciamenti

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#19]
Non è presente nel sistema di tracciamento il pattern MVP, poiché non ha componenti associati ad esso.

**Comment by diegoberaldin** [comment]
Il problema principale è che MVP è stato usato per dividere le sotto-architetture dunque non vi sono direttamente dei componenti che lo implementano! Più che altro è implementato nella divisione strutturale del sistema nelle tre sotto-architetture! Come si fa?

**Comment by RikyTres** [comment]
Risolto tutto!
