### ISSUE TITLE
Modificare l'indirizzo URL delle servlet lato clientpresenter

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#190]
Per rendere il software portabile si necessita la creazione di un file di configurazione in cui il sistemista che installerà l'applicativo dovrà registrare l'indirizzo URL del server.

**Comment by diegoberaldin** [comment]
La nostra parte client non deve essere installata. Il codice JavaScript è scaricato da tutti i client  nel momento in cui caricano la nostra pagina principale, di conseguenza è sufficiente cambiare quegli URL nel codice che sta sul server e poi i client si tirano giù i dati corretti.

Se non ti piace avere le URL disseminate nei vari sotto-presenter e nel `CommunicationCenter` le potremmo raccogliere un qualcosa di "globale" ma LUI disapproverebbe; Tres e io stiamo cercando di limitare allo stretto indispensabile l'uso dello scope globale.

La mia coscienza comunque rimorde perché so che è un peccato di certo non veniale.. finirò per questo nel girone dei programmatori creativi che è certamente vicino al Cocito nell'Inferno profondo

**Comment by diegoberaldin** [comment]
Sistemato con lettura di file XML di configurazione che risiede sul server. La lettura viene fatta in ogni presenter con la funzione privata `getServletURLs()`.
