### ISSUE TITLE
Immagine Personale

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#203]
Controllare a che stato è l'implementazione lato Server di ciò e concludere l'implementazione del lato client.
Verificare anche l'implementazione nella modifica dei dati della modifica dell'immagine profilo.

**Comment by marcoskivo** [comment]
nel momento della registrazione dovrebbe essere apposto.. la modifica non credo..

**Comment by marcoskivo** [comment]
da quello che ho capito, non diamo la possibilità di cambiarla.. almeno sul software, ovviamente nei documenti c'è tutto!! ;)
