### ISSUE TITLE
Fare in modo che con registrazione avvenuta si venga anche autenticati

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#212]

**Comment by diegoberaldin** [comment]
Corretta questa cosa nel server con b7ff95a0ad1ea4665b60f73cc29d27bbca6bacdf, ora dovrebbe essere tutto a posto! Quando siamo sicuri che tutto funziona si potrà chiudere la issue...

**Comment by marcoskivo** [comment]
c'è gia un'altra issues #256
