### ISSUE TITLE
[PresenterMediator] Controllare che onFiltredApplyedByParam() e onFiltredApplyedByGroup() non siano inutili

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#213]
Le funzioni citate nel nome della issue non dovrebbero servire nel PresenterMediator perche dovrebbero essere delle semplici funzioni interne del AddressBookPanelPresenter.
Controllare e valutare se è il caso di toglierle.

Nel caso non sia necessario toglierle allora togliere i //FIXME dal codice.

**Comment by diegoberaldin** [comment]
Lasciamoli lì perché male non fanno. Tanto fanno solo l'inoltro all'AddressBookPanelPresenter :smile:
