### ISSUE TITLE
richiamare servlet quando effettuo o ricevo chiamata

### ISSUE THREAD

**Issue by marcoskivo** [SoftwareSynthesis/SoftwareEngineeringProject#222]
da richiamare quando effettivamente la chiamata è stata accettata

**Comment by diegoberaldin** [comment]
Esattamente _quale_ servlet occorre richiamare?

**Comment by RikyTres** [comment]
Sono le servlet per il registro di chiamata (credo)

**Comment by diegoberaldin** [comment]
@marcoskivo  perché hai chiuso? C'è qualcosa che dovremmo sapere? Non esisterà mai quel controller?

**Comment by diegoberaldin** [comment]
Controller fatto, beh insomma... che sia testato è un altro discorso...
