### ISSUE TITLE
Fare il Dis-Lessico per Labyrinth Pointer

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#224]
https://github.com/SoftwareSynthesis/SoftwareEngineeringProject/wiki/disLessico#labirint-pointer

**Comment by diegoberaldin** [comment]
Segnalo anche il pattern **Endless waiting pointer** concepito dalla geniale mente di @Rizzi-Andrea..

**Comment by diegoberaldin** [comment]
aggiungere anche **TresNotation** e **Garbage Collector** al dis-Lessico!
