### ISSUE TITLE
dubbi su UserData.java

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#234]
Non sono sicuro di aver capito quale senso abbia il campo dati `Set<ICallList>` dentro `UserData`, trovo inoltre leggermente fuorvianti i nomi dei metodi `addCall(ICallList call)` e `removeCall(ICallList call)`: stiamo operando su liste di chiamate o su chiamate singole?

PS. Non per fare il cagacazzo ma plurale di "entry" è "entries"...

**Comment by diegoberaldin** [comment]
Ho capito il primo punto perché mi hai spiegato a voce il Labyrinth pointer... rimane la seconda cosa...

**Comment by meneghinello-andrea** [comment]
Ogni utente ha un elenco di degglio delle conversazioni.

**Comment by diegoberaldin** [comment]
Mi riferivo all'errore ortografico, ma tant'è Tullio non guarda il codice....
