### ISSUE TITLE
javadoc obsoleto in CredentialLoader.java

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#236]
Il costruttore è rimasto quello coi parametri vecchi. Lasciare in giro documentazione obsoleta è un ottimo modo di generare Labyrinth Pointer, ma non facilita il compito a chi verifica il codice.

@meneghinello-andrea per favore butta un occhio alle segnalazioni di bug.

**Comment by meneghinello-andrea** [comment]
Ora controllo. Grazie mille dell'avviso e chiedo scusa per gli errori commessi

**Comment by meneghinello-andrea** [comment]
Ho aperto davanti a me il costruttore della classe CredentialLoader in org.softwaresynthesis.mytalk.server.authentication e la documentazione hai i parametri corretti.

**Comment by diegoberaldin** [comment]
Inspiegabilmente, non stavamo guardando lo stesso codice... dopo che mi si è sconvolto tutto ho visto anch'io i parametri corretti. Scusa per la segnalazione inutile.
