### ISSUE TITLE
test di CredentialLoader

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#237]
Non capisco sinceramente cosa tu voglia fare con il cast a riga 41 di CredentialLoader, che però fallisce perché non è possibile convertire un Callback in un Loader (che te lo vengo a dire...). D'altronde, è anche impossibile mettere lì un costruttore di XXXLoader (indipendentemente dal fatto che siamo in un ciclo) dal momento che i costruttori di `NameLoader` e `PasswordLoader` non prendono un callback come parametro ma se li creano al volo e lo passano al costruttore della superclasse. La cosa non è così banale e forse denota qualche scricchiolio nella riprogettazione di authentication, quindi preferisco non metterci mano e limitarmi a segnalare il problema.

**Comment by meneghinello-andrea** [comment]
Gli elementi del vettore callback ricevuto come parametro del metodo handle nella classe CredentialLoader hanno tipo statico Callback ma hanno tipo dinamico Loader. Loader infatti è una sottoclasse di Callback. Tale vettore viene dichiarato ed inizializzato nella prima parte del metodo login() in AuthenticationModule. Quindi secondo me il cast è possibile tant'è che non mi risultano errori, se tu vedi qualcosa di differente ti prego cortesemente di segnalarmi il problema.
In attesa di una cortese risposta.

**Comment by diegoberaldin** [comment]
Mi scusi, stavo cercando di aggiustare il test vecchio senza buttarlo via e rifarlo da capo, lì venivano usati NameCallback e PasswordCallback per il vettore di Callback da passare a `handle`, mi era sfuggito che dovessero essere dei Loader. Mi voglia perdonare per la svista. Distinti saluti.
