### ISSUE TITLE
[AuthenticationModuleTest] getto la spugna

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#238]
Per l'ennesima volta, ha vinto lui. Io questa classe non riesco a testarla, nemmeno indirettamente tramite il LoginContext.

Non riesco a farlo andare in nessun modo, dà una ClassCastException ma stavolta non mi sembra sia colpa mia che uso parametri di tipo sbagliato. Non ci capisco più nulla, quindi chiedo a chi ne capisce più di me di ultimare il test.

Cordiali saluti.

**Comment by meneghinello-andrea** [comment]
A che punto genera un ClassCastException?

**Comment by diegoberaldin** [comment]
Nell'initialize(...) di AuthenticationModule quando fa

``` java
this.handler = (CredentialLoader)handler;
```

se non hai modo di lanciare il test nei prossimi giorni, ti faccio vedere mercoledì...

**Comment by meneghinello-andrea** [comment]
Grazie mille ora vado e ricontrollo. Quella riga mi sembra sia inserita nel metodo initialize() che viene invocato dal Framework.

**Comment by meneghinello-andrea** [comment]
Ho sistemato. L'errore che ho riscontrato è dovuto al fatto che avevo fatto una cosa troppo specifica nell'initialize() ed essendo invocato dallo stesso JAAS lui non può sapere delle mie sottoclassi.

**Comment by diegoberaldin** [comment]
Mi dispiace romperti l'anima per l'ennesima volta, ma il problema mi pare che sia stato solo rimandato, ora il ClassCastKaputt avviene quando si cerca di estrarre la strategia, a riga 118 di AuthenticationModule:

``` java
strategy = ((CredentialLoader)this.handler).getSecurityStrategy();
```

:(

**Comment by meneghinello-andrea** [comment]
Risolto il problema
