### ISSUE TITLE
Tipo di ritorno booleano per il client

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#239]
Ciao,
quando devo ritornare al client un valore booleano è suficente:
String result = "true";
PrintWriter writer = response.getWriter();
writer.writeResult(result);

**Comment by diegoberaldin** [comment]
Sì, sono sicuro al 99,(9)% che sia sufficiente quello!

**Comment by meneghinello-andrea** [comment]
Mi ricordo mi avevi accennato al fatto di virgolette in più e questa mattina non mi ricordavo se erano quelle. Grazie mille. A questo punto chiudo la richiesta.
