### ISSUE TITLE
Tipo errore per il client

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#240]
Ciao,
sto guardando le vecchie servlet e vedo che in caso qualcosa vada storto a volte si ritorna false a volte null. Continuo questa tradizione?

**Comment by diegoberaldin** [comment]
In teoria non cambia niente perché nei linguaggi stupidi a tipizzazione dinamica come JavaScript `false`, `null` e `undefined` vengono tutti valutati a falso e siccome abbiamo sempre un controllo del tipo

``` javascript
var response = JSON.parse(request.responseText);
if (!response) {
  alert("Te gh'è fato 'na monada!");
}
```

non dovrebbe cambiare niente. In realtà però non sono convinto che sia una buona tradizione, forse sarebbe il caso di uniformare e ritornare sempre la stessa cosa in caso di errore.
[questi sono i miei 2 centesimi di opinione]

Vorrei che intervenisse anche @RikyTres per dare il suo parere.

**Comment by meneghinello-andrea** [comment]
Va bene, ti ho posto questa domanda poiché nella classe AbstractController dove viene ridefinito il metodo execute() dell'interfaccia IController() il codice che avevamo pensato è il seguente:

```
if (this.check(request))
{
       this.doAction(request, response);
}
```

cosi facendo però se il controllo fallisce il controller termina silenziosamente, ossia al client non giunge alcun tipo di risposta. Se si decidesse di uniformare la risposta mi sarebbe sufficiente fare un ramo else che si occupa di mandare in output una risposta di fallimento comune, altrimenti si dovrebbe definire un metodo astratto, ad esempio `doError(response)` ridefinito da ogni controller in modo che si possa ritornare null, false di caso in caso

**Comment by diegoberaldin** [comment]
Questo, a mio avviso, fa pendere **pesantemente** la bilancia in favore dell'uniformità delle risposte in caso di fallimento :)

**Comment by meneghinello-andrea** [comment]
Deciso di usare un unico messaggio
