### ISSUE TITLE
[DAO] getUserDatas e generics

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#241]
Per eliminare il ciclo finale in `getUserDatas(...)`, @meneghinello-andrea hai per caso provato questo?

``` java
List<IUserData> userList = (List) collection;
```

**Comment by diegoberaldin** [comment]
Se sai che le cose contenute nella collection hanno **tutte** il tipo giusto, dovresti aggirare i controlli del compilatore :)

**Comment by meneghinello-andrea** [comment]
Io avevo provato:

```
List<IUserData> userList = (List<IUserData>)select.execute();
```

e questo era segnalato come errore da parte del compilatore.

**Comment by diegoberaldin** [comment]
Tutto _sembra_ a posto, il test è passato e ho cancellato la parte commentata del metodo, quindi chiudo.
