### ISSUE TITLE
[DAO] final classes

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#242]
È proprio necessario che tutti gli util siano final? Mi tarpa un po' le ali questa cosa...

**Comment by diegoberaldin** [comment]
Mi tarpa anche qualcos'altro a dire il vero...

**Comment by meneghinello-andrea** [comment]
Non è necessario siano fianl. Comunque quando ci vediamo ne discutiamo un attimo e caso mai tolgo i final. Non dovrebbe succedere nulla per i test

**Comment by diegoberaldin** [comment]
Ci siamo capiti chiacchierando per andare verso la stazione. Sono ritornate `final` così siamo tutti contenti! :)
