### ISSUE TITLE
[AbstractController - dubbio idiota] variabile userMail di istanza o di classe?

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#246]
Mi accingo a testare (quel che è testabile) di AbstractController. Leggendo il codice, però, mi è sorta una domanda: quel campo dati non dovrebbe essere marcato `static` della serie:
- sta lì ed è visibile a tutte le sottoclassi (dovunque usi `super.getUserMail()`);
- lo setta `LoginController` (come in effetti fa) e da lì resta settato per tutte le altre sottoclassi di AbstractController.

Se invece è di istanza, una volta morto LoginController non c'è più e nemmeno lo vedono gli altri che nella loro superclasse (sottooggetto) non ce l'hanno mai avuto. Anche perché il `setUserMail(...)` è chiamato solo una volta e solo in LoginController...

P.S. I metodi accessori possono anche rimanere non statici, l'importante è che il valore che leggono sia sempre lì presente.

P.P.S. In realtà non so se una volta che il classloader carica una classe, tutta la robaccia statica rimanga sempre in memoria anche quando non ci sono istanze "vive" della classe...

**Comment by diegoberaldin** [comment]
In realtà il problema è ancora diverso, non può nemmeno essere `static` perché se no diventa automaticamente condivisa fra tutti i controller di tutti gli utenti... Qui chiudo e ne parliamo a voce che mi sa che sono stupido io e mi sono perso qualche pezzo in giro...

**Comment by meneghinello-andrea** [comment]
Ottima osservazione, il problema sussiste. Ora mi accingo a trovare una soluzione

**Comment by diegoberaldin** [comment]
Può essere un'idea fare come facevamo una volta ed estrarre lo username dalla sessione associata alla richiesta HTTP e rinunciare a quel campo dati? Notificami la soluzione che trovi che cambio i test...

**Comment by meneghinello-andrea** [comment]
Stavo pensando, nel controller che si occupa di fare il login salvo nella sessione la variabile '''context''' voglio vedere se da li riesco ad estrarre attraverso i Principals lo username

**Comment by meneghinello-andrea** [comment]
Dovrei aver risolto il problema. Non ho apportato modifiche radicali. Ora lo username lo recupero dalla sessione
