### ISSUE TITLE
[Controller] 

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#247]
Quando nei controller usi il DataPersistanceManager nel metodo doAction() non crearlo con il new. Per creare una nuova istanza usa il metodo getDAOFactory() della super classe AbstractController. Cosi diamo a Diego maggiore possibilità di test nei controller.
In generale i new sarebbero da evitare.

**Comment by marcoskivo** [comment]
sempre fatto!

**Comment by meneghinello-andrea** [comment]
Ottimo, allora chiudo
