### ISSUE TITLE
[RegisterController] campi dati obbligatori

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#255]
Il nuovo controller, a differenza della vecchia servlet, non fa nessun controllo sul fatto che i quattro parametri obbligatori (email, password, domanda e risposta) siano forniti nella richiesta.

Al contrario, il metodo getParameter che nel caso di parametro nullo restituisce la stringa vuota permette al doAction di continuare inserendo "" anche nel database per quei campi obbligatori, e stampa sulla risposta un JSON con stringhe vuote anche nei campi obbligatori.

Siamo sicuri che sia questo quel che vogliamo?

p.s. Non riesco a entrare nell'if di r.78 perché il `new FileOutputStream(...)` mi muore con una FileNotFoundException... si può barare anche qui in qualche modo o devo rassegnarmi a lasciar fuori quelle righe?
:skull:

**Comment by diegoberaldin** [comment]
La mia opinione è che è meglio barare, perché la situazione di copertura è **disastrosa** e rischiamo di non riuscire nemmeno a mantenere le promesse.
P.S. Giusto per la cronaca ci sono certi nostri concorrenti che hanno il 100% di statement coverage...

**Comment by marcoskivo** [comment]
ti rispondo per quanto riguarda il salvataggio del file perché l'ho fatto io. Quel new FileOutputStream() serve proprio per creare un file vero e proprio nel percorso che gli passi come parametro.. non so perché ti dia quell'errore e non saprei nemmeno come fare per "barare".. prova a crearti un file nel giusto percorso prima di lanciare il test ma non credo..

**Comment by diegoberaldin** [comment]
Barare sarebbe non fare il `new FileOutputStream(...)` ma chiamare un metodo che lo fa al posto nostro, come vi ho chiesto di fare per il getDAOFactory e getSecurityStrategyFactory...
