### ISSUE TITLE
[RegisterController] login dell'utente

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#256]
Se non sbaglio si era (più o meno sempre) detto che contestualmente ad una registrazione con successo sarebbe avvenuto il login dell'utente al sistema. Restituendo il JSON con i dati dell'utente il client è soddisfatto e "crede" di essere autenticato.

Ma lato server non dovrebbe essere fatto qualcosa di più? Non dovrebbe esserci da qualche parte un `context.login()` o cose simili, come avviene effettivamente nel controller di login?
:skull:

**Comment by marcoskivo** [comment]
fatto
