### ISSUE TITLE
[GetCallsController] il solito getUserMail()

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#258]
_[informazioni di servizio mode: ON]_
ho iniziato a scrivere altri test perché in `authentication.controller` sono attualmente bloccato da tutte le segnalazioni 25[1-7] )
_[informazioni di servizio mode: OFF]_

Noto con piacere che non c'è più duplicazione di metodi, purtroppo c'era al solito un `super` di troppo (non devo avere il getDAOFactory() legato **staticamente** alla superclasse altrimenti non posso fare un tubo nei test!). Ripeto questa cosa per la n-esima volta (so di essere uno scassaminchia) sperando che sia compresa dai programmatori.

Tuttavia vedo il solito getUserMail() rispetto al quale non so come comportarmi. Ho già chiesto lumi in #252 e #257, per favore qualcuno mi dica cosa fare! Io abbozzo il test per ora, so che fallirà, ma **il tempo davvero stringe**...

:skull:

**Comment by diegoberaldin** [comment]
Può essere una soluzione questa?

``` java
  HttpSession session = request.getSession(false);
  String email = session.getAttribute("username");
```

era quel che si faceva nelle vecchie servlet, se non sbaglio...

**Comment by diegoberaldin** [comment]
Lo stesso problema si ripresenta anche in AddContactController... siccome fa fallire tutti i test, qualcuno potrebbe per favore darmi una risposta? :skull: 

Se non posso eseguire i test non posso vedere nemmeno se ci sono errori miei disseminati nel codice di test, rallentando ulteriormente la già di per sé lenta attività di verifica perché andranno corretti in un secondo momento quando non mi ricorderò più cosa volevo testare...

**Comment by marcoskivo** [comment]
queste cose io non le so.. l'"architettura" l'ha fatta mene, io mi sono limitato a trascrivere le ex servlet adattandole.. quando ho chiesto come fare per recuperare la mail mi aveva detto di usare il getUserMail().. io non so come altro fare, lo sa mene..

**Comment by diegoberaldin** [comment]
Siccome mi aveva detto espressamente che si trattava un errore in #246 e aveva detto di aver risolto in e79e16b non so nemmeno io che cosa dirti!

**Comment by diegoberaldin** [comment]
corretto, errore mio SCUSATE
