### ISSUE TITLE
[abook.controller.*] parametri obbligatori

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#262]
Non viene fatto nessun controllo nemmeno in questi controller, un simile problema era stato segnalato in #255 , per il fatto che eventuali parametri non siano presenti nella richiesta.

È mia opinione che un controllo del genere vada fatto, vuoi per evitare di fare operazioni senza senso o dannose nel caso di richieste malevole, vuoi per mettersi al riparo da eventuali errori del client. Le richieste nel client sono infatti state rimaneggiate più volte seguendo tutte le iterazioni (prima per togliere le operazioni e inoltrarle agli indirizzi delle servlet, poi per rimetterci le operazioni, ecc. ecc.) quindi gli errori possono benissimo esserci!

P.S. Mi sembra che le vecchie servlet fossero fatte meglio di questi control-cosi...
:skull:

**Comment by diegoberaldin** [comment]
Dimenticavo: `getUserMail()` ovunque anche in questo package...

EDIT: Errore mio, sistemato!

**Comment by marcoskivo** [comment]
io non ho fatto altro che prendere le vecchie servlet e sistemare il codice.. non ho aggiunto ne tolto niente..
spero domani ci sia mene cosi sistemiamo una volta per tutte questi casini..
