### ISSUE TITLE
[AddInGroupController] testAddNotOwnedGroup non superato

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#263]
Potresti per favore controllare il risultato `true`/`false` dell'operazione di inserimento?

**Comment by meneghinello-andrea** [comment]
Fatto il controllo sull'operazione di insert e creato un trigger nel database che esegue il controllo che l'utente venga inserito in un gruppo di appartenenza di chi ha avviato l'operazione. Rimango in attesa del risultato del test

**Comment by diegoberaldin** [comment]
Non si vede in questo test, sarà nei TI che non faremo mai! :)
