### ISSUE TITLE
Gruppo "addrBookEntry" nel server... Non esiste più?

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#265]
Deve tornare ad esistere perche richiede una riprogettazione del client che non abbiamo tempo di fare!

**Comment by diegoberaldin** [comment]
RegisterController deve essere cambiato.
p.s. Mene sostiene che se aveva detto a Schivo che il campo id_Group poteva essere `null` in certi casi lo ha detto senza volerlo. Quindi addrBookEntry rimane.

**Comment by marcoskivo** [comment]
sistemato
