### ISSUE TITLE
[SearchController] nella lista degli utenti è normale che non ci sia lo stato?

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#267]
Se la risposta è negativa, parlare prima con me che devo correggere il test per favore. La modifica al codice dovrebbe idealmente ricalcare quanto fatto per GetContactsController, cioè aggiungere un metodo nuovo del tipo

``` java
    String getContactState(IUserData contact)
    {
        String state = ControllerManager.getState(contact.getId());
        return state;
    }
```

e richiamarlo in fase di costruzione della stringa JSON da stampare.

Grazie.

**Comment by meneghinello-andrea** [comment]
Ora al client per ogni utente trovato viene restituito anche il suo stato. Per fare ciò è stato aggiunto un metodo, con visibilità package, che si chiama getContactState(IUserData). Questo metodo è identico a quello presente nel controller getContactController

**Comment by diegoberaldin** [comment]
Perfetto! :)
