### ISSUE TITLE
[UpdateMessageController] nessun controllo se  chi inoltra la richiesta è il destinatario del messaggio

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#268]
La cosa potrebbe essere risolta confrontando il riferimento ritornato da getReveiver() con l'utente. Non mi sembra un comportamento "voluto" e "normale"

Domanda progettuale: a cosa serve esattamente avere in DataPersistanceManager il metodo `List<IMessage> getMessage(IUserData receiver)` e avere in UserData il metodo `Set<IMessage> getMessages()`? Non sono due modi di fare la stessa cosa? Labyrinth Pointer?

**Comment by meneghinello-andrea** [comment]
Hai ragione...non ha senso.

**Comment by marcoskivo** [comment]
sistemato tutto!
