### ISSUE TITLE
Aggiornare Stub per gestire tutte le richieste da parte del client

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#269]

**Comment by marcoskivo** [comment]
credo a sto punto sia meglio fare le prove con il server..

**Comment by diegoberaldin** [comment]
Una volta di fronte a una mia osservazione del genere Tres mi ha ribattuto «Questo è un Labyrinth pointer, cioè un ottimo modo di moltiplicare le possibili fonti di errore perché il bug può essere sia da una parte che dall'altra»...

Però dal momento che non abbiamo tempo, sono d'accordo con Schivo!! :+1:

**Comment by marcoskivo** [comment]
quindi chiudo!
