### ISSUE TITLE
[PushInbound] stato e disconnessione

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#272]
L'informale resoconto della verifica di questa classe è che  ho modificato nel ramo 5 del mega-branch il fatto che si manda la rappresentazione in stringa dello stato in formato maiuscolo, dal momento che il client se lo aspetta in minuscolo.

**Comment by diegoberaldin** [comment]
p.p.s. Altro problema rilevato (non coi test perché non posso farlo) ma con analisi statica e un po' di debugger... Cosa succede sempre nel ramo 5 quando si trova un contatto nella rubrica che però non è connesso? In quel caso il mio caro metodo _statico_ findClient(...) ritorna correttamente `null` ma prima di farse `sendTo.getWsOutbound()` non si fa alcun controllo per verificare se `sentTo` sia `null`. La cosa a mio avviso dovrebbe essere gestita...

**Comment by diegoberaldin** [comment]
p.p.p.s. (chiedo scusa se arrivano a sprazzi i miei commenti) Mi confermi che nel ramo 6 deve essere fatto solo quello? Rimandare a chi mi ha inviato il messaggio di testo `6|`?

**Comment by marcoskivo** [comment]
ho sistemato e aggiunto anche la chat.. non so se devi modificare dei test..

**Comment by diegoberaldin** [comment]
Sì dovrò farlo, provvedo entro lunedì a risistemare il tutto!
