### ISSUE TITLE
Trovare modo di copiare per valore un elemento JS

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#273]
@diegoberaldin mi serve effettuare una copia di un Object... Dovremo trovare il modo di farlo...

**Comment by diegoberaldin** [comment]
Di che oggetto si tratta esattamente? se non è qualcosa con proprietà "ereditate da superclassi" o altro, potrebbe bastare un `var copy = JSON.decode(JSON.encode(original));`?
EDIT: È orrendo lo so! :grin:

**Comment by RikyTres** [comment]
Soluzione orrenda trovata... Per futuri utilizzi:
`var copy = JSON.parse(JSON.stringify(original));`
