### ISSUE TITLE
Trovare errore per cui esce dalla pagina in qualche caso (vedi descrizione issue)

### ISSUE THREAD

**Issue by RikyTres** [SoftwareSynthesis/SoftwareEngineeringProject#275]
Nei seguenti casi viene ricaricata la pagina:
• [AccountPresenter] quando modifico i dati e premo il pulsante "modifica"
• [GroupPresenter] quando annullo l'operazione di aggiunta di contatti ad un gruppo

**Comment by marcoskivo** [comment]
quando faccio la registrazione e immediato successivo login

**Comment by marcoskivo** [comment]
da quello che ho capito, va ricontrollato tutti i form..

**Comment by diegoberaldin** [comment]
Era quel che mi diceva Tres oggi, solo che non ho capito come si può risolvere :(

**Comment by marcoskivo** [comment]
sistemati con il preventDefault()
