### ISSUE TITLE
Query modificate

### ISSUE THREAD

**Issue by marcoskivo** [SoftwareSynthesis/SoftwareEngineeringProject#282]
27/05 --> query su getGroups(IUserData user)

**Comment by diegoberaldin** [comment]
Ok, ricevuto! Alla prossima iterazione sui test correggo ma intanto aspetto che si "bufferizzino" un po' di cambiamenti quindi non ti allarmare se non correggo subito!

**Comment by marcoskivo** [comment]
tutte quelle dei message perchè c'era il nome della tabella "Messages" al posto di "Message"

**Comment by marcoskivo** [comment]
public List<IGroup> getGroup(IUserData owner)

non confronta piu l'utente ma l'id

**Comment by diegoberaldin** [comment]
Visto tutto oggi e aggiornate tutte le query di DataPersistanceManagerTest. Grazie per avermelo ricordato!
