### ISSUE TITLE
DeleteGroupController

### ISSUE THREAD

**Issue by marcoskivo** [SoftwareSynthesis/SoftwareEngineeringProject#284]
facendo il controllo
if (group.getOwner().equals(myUser))
mi dava questa eccezione "could non initialize proxy - no session"..
ho cosi applicato un barbatrucco, ossia confrontare l'id dell'utente e non l'intero oggetto IUserData..
Non so se vada bene, in questo modo funziona ma a @diegoberaldin ("puffo dei test"!) la decisione!

**Comment by diegoberaldin** [comment]
Citando il Grande Fuffo

> Ricevuto e recepito

**Comment by marcoskivo** [comment]
ottimo chiudo!
