### ISSUE TITLE
rimuovere PushInbound quando faccio logout

### ISSUE THREAD

**Issue by marcoskivo** [SoftwareSynthesis/SoftwareEngineeringProject#285]
come facciamo a richiamare la pushinbound dal controller logout??

**Comment by diegoberaldin** [comment]
Puoi contestualizzare meglio per favore? Se la cosa serve per notificare il cambiamento di stato (e dire agli altri che il client «si sta **sloggando**») ci abbiamo pensato noi nel client...
[dove "noi" vuol dire Tres & Tres perché io sono una presenza molto silenziosa]

**Comment by marcoskivo** [comment]
fatto
