### ISSUE TITLE
Manuale d'installazione

### ISSUE THREAD

**Issue by B1uRay** [SoftwareSynthesis/SoftwareEngineeringProject#286]
E' un lavoretto facile facile, il manuale d'installazione è composto principalmente da come installare/configurare il server visto che la parte client è semplicemente un "accendi internet e vai alla pagina, pirla!".

Per l'RQ avevo buttato giù qualcosa io con qualche dritta e Cardin mi aveva chiesto di approfondire visto che praticamente ho fuffato alla grande...

C'è qualche buon "serverista" che sappia scrivere due righe chiare su come installare il tutto? E' una cosa da massimo un ora (produttiva), non di più, basta seguire le indicazioni sul doc che c'ha lasciato il prof. ;-)

EDIT: Assegno a Mene visto che mi aveva aiutato la volta scorsa ed è quello che con il server ha "giocato" di più. :-)

**Comment by diegoberaldin** [comment]
>  "accendi internet e vai alla pagina, pirla!"

Laddove la pagina dà un bel 404 :facepunch: 

Comunque, :+1:

**Comment by meneghinello-andrea** [comment]
Rivisto ed inserita un pò di fuffa!!! Resta da valutare lo stile della fuffa e siamo a posto!!! ;)
