### ISSUE TITLE
[DdP] aggiornare onLoadedView del CESSO per viste di terzo livello

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#289]
Da documentare con gli opportuni accorgimenti dal momento che le viste di terzo livello non esitono ufficialmente.

Eliminare però dalla definizione di prodotto i metodi `onShowAnswerBox` e `onRemoveAnswerBox` del cesso, perché SONO MORTI!  Lux perpetuă luceat eis, Requiescant In Pacē, Amen!

**Comment by RikyTres** [comment]
Comittato le mie modifiche di ieri (credevo di averlo già fatto)

**Comment by diegoberaldin** [comment]
Parlavo di documentazione ed era un promemoria per me più che altro...

**Comment by RikyTres** [comment]
Ho visto poi... ;) (l'avevo chiusa per sbaglio)

Comunque ese ti serve vedere come è fatto onLoadedView ora c'è...

**Comment by diegoberaldin** [comment]
Ok, grazie! Stamattina se ho tempo vorrei iniziare anche a documentare anche la BathTubView (a.k.a. CommunicationView), solo che se già avevo dubbi nel presenter non oso immaginare nella vista! Mal che vada userò Cruftory Method e produrrò fuffa, tanto non se ne accorgono!

P.S. Per il Monolith, invece, si apre un bivio, anzi... un trivio:
- tenere la descrizione vecchia  ^_^
- tentare di rifarla ma non so se verrà meglio
- aggiornare quella esistente alla meno peggio

Il mio sogno sarebbe di finire queste cose oggi in modo da poter iniziare domani seriamente con la verifica, o meglio, con la _falsifica_...
