### ISSUE TITLE
[Lista chiamate]

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#297]
Siccome dobbiamo fornire la possibilità di chiamare utenti non della propria rubrica e durante la visualizzazione della lista chiamate il server ritorna solo l'ID della persona chiamata ed ho visto che tale ID viene cercato in un array nel client che però non possiederà utenti che non sono nella propria rubrica, ci sono quindi due possibilità:
- Modifico la stringa JSON ritornata dal server con tutti i dati dell'utente (ID, cognome, nome, email, + dati chiamata);
- Modifica del client affinché se non trovate il contatto nell'array lanciate una ricerca verso il server.

Sinceramente sono più propenso per la prima perché richiede un minor sforzo e cosi potete eliminare la ricerca dell'utente nei vostri array

**Comment by RikyTres** [comment]
Presa in visione.
Oggi sistemiamo dell'altro. Domani vediamo di sistemare! ;)

**Comment by meneghinello-andrea** [comment]
Va bene, dal server allora vi ritorno l'ID e l'indirizzo mail del contatto nella stringa JSON

**Comment by diegoberaldin** [comment]
Questa cosa è stata fatta, modificando sia nel server che nel client il comportamento... Chiudo!
