### ISSUE TITLE
Diagramma front controller

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#302]
Ho riscontrato la seguente incongruenza nel diagramma che illustra il design pattern front controller nella ST. L'incongruenza sta nella parte bassa del diagramma, ovvero è illustrato che javax.servlet.http.Servlet eredita da org.apache.catalina.webSocket.WebSocketServlet e questo è errato poiché è ControllerManager che eredita da WebSocketServlet.
Quindi in conclusione bisogna modificare la freccia in modo tale che Controller manager implementi javax.servlet.http.Servlet ed erediti da org.apache.catalina.webSocket.WebSocketServlet.

**Comment by diegoberaldin** [comment]
Credo sia stata corretta questa cosa, giusto?
