### ISSUE TITLE
Testo presentazione RA - requisiti soddisfatti e non

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#303]
alla gentile attenzione di @B1uRay 

Ciao Stefano, oggi in pausa pranzo ho messo giù il testo per la presentazione al RA. Puoi buttarci un occhio e dirmi se in linea generale può andare? Mi sono rifatto a quanto ci siamo detti la volta scorsa, ma mi sa che è ancora una bozza cosi cosi. cmq...

Iniziamo esaminando il soddisfacimento dei requisiti. Oggi ci presentiamo con un prodotto software funzionante e in grado di rispondere alla maggior parte dei requisiti discussi con il proponente nel colloquio avuto ad inizio progetto, e presentati in sede di RR nella prima revisione da noi svolta. Nello specifico il team ha soddisfatto il 95% dei requisiti obbligatori, il 45% dei facoltativi ed il 78% dei requisiti desiderabili. Risultato sostanzialmente in linea con quanto atteso.

In merito ai requisiti obbligatori, l'unico requisito venuto a mancare riguarda la mancanza di informazioni sulla latenza e la qualità del segnale. La motivazione alla base del loro mancato soddisfacimento è dovuta ad una mancanza del dominio tecnologico. Dai nostri studi è infatti emerso che WebRTC non fornisce informazioni utili al calcolo dei suddetti parametri, in quanto l'implementazione degli stessi risulta ancora lacunosa e in fase di raffinamento. Molto probabilmente nei prossimi mesi tale mancanza verrà colmata, in questo modo il nostro software, predisposto ad aggiornamenti come richiesto, potrà implementare anche tale funzione.

Per quanto riguarda invece i requisiti facoltativi, il problema principale sta nell'incapacità dei browser (ovviamente ad eccezione di Chrome) di supportare a pieno le librerie di webRTC. Altro requisito facoltativo giudicato importante ma non raggiunto a causa della scarsità di ore di lavoro preventivate, è la predisposizione dell'applicativo per effettuare chiamate a più di due partecipanti, altra funzionalità che webRTC molto probabilmente renderà di più agevole implementazione rispetto a quanto riscontrato durante le attività di studio sulla stessa, infine il prodotto è predisposto ma non possiede la capacità di file sharing tra utenti.

Infine per quanto riguarda i requisiti desiderabili, si segnala il mancato soddisfacimento dei requisti legati alla  predisposizione dell'applicativo a supportare il multi-lingua nella propria interfaccia grafica.

**Comment by Rizzi-Andrea** [comment]
PS. per il manuale utente ho chiesto a Tres di farmi gli screen che mancano.. stasera torno alle 20:30... e direi che usando quelle dovrei finirlo in 2 orette... mal che vada lo termino martedì sera.

**Comment by B1uRay** [comment]
ok, in linea generale va bene, ti ho cambiato al volo un paio di sottigliezze, giusto per non spalarci (palesemente) mer*a sulla testa ma solo cospargercela attorno. ;-)

EDIT: aggiornato il testo ORA :P

**Comment by Rizzi-Andrea** [comment]
Ok le modifiche dove le hai messe? Cmq si dai... avere una sciarpa di merda mi sembra una valida opzione ad un cappello di merda XD

**Comment by B1uRay** [comment]
ti ho aggiornato una cosina che ci era scappata: non possiamo fare file sharing (pdf-immagini-schifezze) tra utenti. ;-)

**Comment by diegoberaldin** [comment]
Che bel sogno la condivisione dello schermo :)

**Comment by B1uRay** [comment]
Per completezza, allego anche il mio "discorso elettorale", sperando di portare a casa almeno il vostro voto! xD

Passiamo ora al consuntivo finale sulle attività progettuali svolte, prima di effettuare la dimostrazione del programma realizzato.

Analizzando l'ultima attività di validazione svolta, possiamo notare, come è già successo in passato, un discostamento rispetto a quanto pianificato, causato da problematiche di implementazione di alcune funzionalità specifiche del software, come la segreteria o il blocco di un utente specifico da parte dell'utilizzatore, e da un'approfondimento ulteriore sull'usabilità del sistema, in quanto il team ha convenuto nel testare l'applicativo su un campione d'utenza, in modo da valutare l'effettivo impatto dell'interfaccia sugli utilizzatori.

Analizzando più un generale il consuntivo finale, possiamo notare che le ore svolte dai componenti del team sono aumentate rispetto a quanto pianificato inizialmente di due ore a persona nel corso dei mesi, ciò è dovuto soprattutto agli imprevisti affrontati e alla scarsa conoscenza del dominio tecnologico e, più in generale, del modo di operare in un progetto di tali dimensioni, come già più volte ribadito nelle revisioni precedenti, portando il risultato al massimo disponibile delle ore dedicabili al progetto.

Dal punto di vista economico al contrario la stima iniziale è stata tutto sommato rispettata, con un ulteriore investimento da parte del team di circa un centinaio di euro. Quindi un discostamento minimo (praticamente l'1%) e sostanzialmente tollerabile.

Passiamo quindi ora, alla dimostrazione pratica del software.
