### ISSUE TITLE
diagramma delle classi componente Gestione segreteria: freccia AudioVideoMessageProxy->AudioVideoMessage

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#44]
Non è freccia di ereditarietà quanto piuttosto di composizione, parte con diamante nero pieno e arriva con freccia punta nera piena

**Comment by diegoberaldin** [comment]
occorre cambiare anche il diagramma delle classi generale della sotto-architettura server

**Comment by marcoskivo** [comment]
fatto (io e tres)
