### ISSUE TITLE
[PdQ]: suggerimenti sulla modifica del documento

### ISSUE THREAD

**Issue by Rizzi-Andrea** [SoftwareSynthesis/SoftwareEngineeringProject#52]
![Nyancona](https://f.cloud.github.com/assets/2726062/110742/c7f88cb0-6ad1-11e2-991e-ae5616dade8c.png)

In seguito ad una mi personale analisi del documento Piano di qualifica, ho riscontrato i seguenti punti che potrebbero, se lo ritenete sensato, essere modificati/aggiunti:

Su quanto già scritto...

1) Paragrafo 4.1 ... "Il processo di verifica inizierà quando il prodotto di un processo taggiungerà uno stadio che si potrà definire diverso da quello precedente"... mh... ma sulla base di che parametri? come definiamo lo "stato" di un prodotto???

Su ciò che potrebbe essere aggiunto... aggiungere come sezioni:

---

REQUISITI DI QUALITA' DEI PROCESSI:
## Aggiungere dei requisiti di alto livello inerenti alla qualità dei processi. Tali requisiti non fanno parte del sistema di tracciamento (che ricordiamo contenere esclusivamente dei requisiti del prodotto), ma vanno inseriti in tale documento, evidenziando come gli altri requisiti, nel loro essere soddisfatti tramite le relative attività di progettazione e codifica, siano vincolati dai requisiti di qualifica prima citati.

AUTO-VALUTAZIONE DEI PROCESSI:

Eseguire un autovalutazione sul nostro modo di lavorare, in merito ai parametri tipici della QoS (usabilità, scalabilità...) in merito ai processi principali.
## L'auto valutazione dovrebbe mostrare lo storico dei nostri progressi. Mentre il documento e le tecniche usate si aggiorna di volta in volta all'uso migliore, lo storico mostra quali sono stati i nostri progressi in termini di auto valutazione.

AUTO-VALUTAZIONE DEI RUOLI:
## Fornire una autovalutazione generale (Senza nomi) sui ruoli ricoperti durante il progetto (amministratore, responsabile ... ecc) evidenziando gli errori tipici, le conseguenze e ripercussioni su: qualità del prodotto, qualità del processo, morale e atteggiamento dei componenti del gruppo. Fornire delle istruzioni da imporre (da parte del responsabile) per correggere e migliorare tali figure professionali.

AUTO-VALUTAZIONE DEGLI STRUMENTI:

Fornire una valutazione quantificabile, dell'impatto sul lavoro del team, dell'utilizzo degli strumenti.

**Comment by diegoberaldin** [comment]
Grazie mille per le osservazioni, @Rizzi-Andrea! Mi permetto di esprimere il mio parere personale dato che da domani sarò io il responsabile _..sè sè semmai il responsabile del fallimento di tutta la baracca.._

Trovo molto interessanti e pertinenti i suggerimenti in merito all'autovalutazione, soprattutto **dei ruoli** e **degli strumenti**, perché fanno vedere che:
- ci abbiamo provato davvero (che non è poco)
- abbiamo individuato le criticità insite nell'esercizio delle nostre funzioni e nell'uso degli strumenti
- abbiamo davvero imparato qualcosa -> siamo maturati nel corso del progetto
- permettono a chi viene dopo di imparare dagli errori dei suoi predecessori

In fondo credo che sia questo ciò che il corso di IS si propone di insegnarci _..anche se in modo un po' drastico.._

Mi impegno pertanto a prendere in considerazione le istanze da te presentate e a tradurle negli opportuni "ticket" di granularità inferiore in vista della prossima consegna! Quando saranno inseriti nella lista delle issue, se ti ritieni soddisfatto, puoi chiudere questa segnalazione, altrimenti lasciami qui sotto i tuoi commenti.

**Comment by Rizzi-Andrea** [comment]
La ringrazio per aver giudicato favorevolmente il mio operato. Sono sicuro che sotto la sua supervisione il team raggiungerà standard qualitativi eccellenti.

Resto in attesa di future considerazioni sull'argomento.

**Comment by diegoberaldin** [comment]
Allora, per la prima domanda ho aperto la #53 dopo aver guardato nel quaderno cosa trovavo al riguardo. Siccome le altre tue osservazioni sono un po' complesse, ho pensato di aprire un'opportuna [sezione](https://github.com/SoftwareSynthesis/SoftwareEngineeringProject/wiki/Chi-ha-paura-del-PdQ-cattivo%3F) nel nostro wiki, sperando nella collaborazione di tutti.

**Comment by diegoberaldin** [comment]
Confermo che ho spremuto nel [wiki](https://github.com/SoftwareSynthesis/SoftwareEngineeringProject/wiki/Chi-ha-paura-del-PdQ-cattivo%3F) tutto quel che mi veniva in mente, ora sta agli altri intervenire e integrare!
