### ISSUE TITLE
[NdP] inserire riferimento a Javadoc e relativo set di commenti

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#54]
Da inserire una sottosezione di "Codifica" nelle norme con le istruzioni e i vincoli per i programmatori che si ritengono necessari.

**Comment by diegoberaldin** [comment]
Decisione arbitraria dato che nessuno rispondeva alla segnalazione. Abbiamo gli strumenti per essere democratici e non li usiamo, _che triste!_ (cit.)

**Comment by Rizzi-Andrea** [comment]
un issues aperto 21 giorni fa... triste davvero... forse dovrei killarlo! Potrei occuparmene io, ma non mi è del tutto chiaro cosa dovrei fare. @diegoberaldin  sai spiegarmi?

**Comment by diegoberaldin** [comment]
Se utilizzeremo Javadoc (cosa che può essere desiderabile) dobbiamo scriverlo nelle NdP oppure nell'introduzione alla DdP.

In ogni caso questo ci obbliga a scrivere codice del tipo:

``` java
/**
 * Representation of a terminological entry.
 * @see TermBase
 * @author diego
 */
public class Term {
    /**
     * Equality operator for terms.
     * @param obj: the other object to be compared with
     * @return <code>true</code> if the two terms share the same language and lemma
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == null || !(obj instanceof Term))
            return false;
        Term other = (Term) obj;
        return lemma.equals(other.lemma) && lang.equals(other.lang);
    }
}
```

dove le cose da notare non sono lo spaghetti code ma l'uso di `/** ... */` per i commenti, i comandi `@see`, `@author`, `@param`, `@return`, `<code>...</code>` [eccetera](http://it.wikipedia.org/wiki/Javadoc#Funzionamento).

Diciamo pure che sarebbe buona norma usarlo, è certamente una best practice...

**Comment by Rizzi-Andrea** [comment]
be piuttosto che farla a mano direi si di farla. Prendo in consegna l'issues e vedo come funziona questo strumento.

**Comment by B1uRay** [comment]
fatto e finito, anche per la parte relativa alle norme su javascript. Da verificare.

**Comment by Rizzi-Andrea** [comment]
Controllo ora, poi chiudo!

**Comment by Rizzi-Andrea** [comment]
Ottimo!
