### ISSUE TITLE
intestazione file sorgenti

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#55]
Domanda a tutti: secondo voi è opportuno definire un'intestazione per i file sorgenti, del tipo nome del file, versione, data creazione, tabella delle modifiche, licenza e quant'altro? Usate pure :+1: o :-1: qui sotto vediamo poi che fare... se la risposta del team è positiva occorrerà aprire un ticket e modificare le NdP.

**Comment by B1uRay** [comment]
Tullio non li guarda, quindi sarebbe più una convenzione per noi che "per lui". Io inizierei senza e vedrei SE ce n'è una necessità effettiva (esempio: potrebbe bastare la descrizione delle modifiche fatte nei commit magari).

**Comment by diegoberaldin** [comment]
In più non abbiamo nemmeno tenuto conto del fatto che con Github è molto semplice entrare nei commit e vedere le modifiche (se il messaggio del commit non è sufficientemente esplicativo) e lasciare dei commenti sulle righe modificate.. Quindi proposta respinta, mi pare di capire?

**Comment by B1uRay** [comment]
Secondo me (per ora) si, al massimo facciamo un test su qualche file e vediamo se veramente ci da benefici ed eventualmente quanto tempo ci porta via. ;-)

**Comment by diegoberaldin** [comment]
Allora non lo dobbiamo normare, presumo.. Altre idee in merito? (es @Rizzi-Andrea)

**Comment by Rizzi-Andrea** [comment]
Il responsabile ha detto NO
