### ISSUE TITLE
[DdP] convenzioni di scrittura

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#56]
Scrivo qui giusto per ricordarmi che ne dobbiamo parlare: secondo voi è sensato introdurre delle convenzioni, come usare colori diversi per il testo, nella DdP (ad es. un colore per gli attributi, uno per i metodi e uno per le eccezioni)?
Secondo me, sinceramente, rende un documento tecnico un po' troppo "arlecchinoso"! :tada:  Vabbè che è carnevale ma non c'è motivo di stare allegri qua...

**Comment by B1uRay** [comment]
Si potrebbe fare, tutto sommato renderebbe molto più intuitiva e pratica la lettura rispetto ad un impaginazione convenzionale e monocromatica.
Aggiorneremo le norme eventualmente, non dovrebbe essere troppo complicato. ;)

**Comment by diegoberaldin** [comment]
O aggiorniamo le norme oppure si potrebbe anche inserire nell'introduzione della DdP una specie di legenda. Tra l'altro, per facilitare la lettura potremmo inserire anche dei riferimenti incrociati e, a questo scopo, nell'indice ho marcato tutte le sezioni e le sottosezioni con delle opportune `\label{}`.

**Comment by diegoberaldin** [comment]
Non avendo ricevuto alcun parere contrario, mi attengo a quanto deciso con gli altri progettisti.
ATTENZIONE: per far funzionare i collegamenti ipertestuali si raccomanda di usare `\classname{nomedellaclasse}` per le classi dello stesso package mentre  `\hyperref[nomedellaclasse]{\ttfamily{}nomequalificatocompletodellaclasse}` per le classi che non sono dello stesso package!
