### ISSUE TITLE
[AR] diagrammi casi d'uso

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#71]
Vanno esportati da Concept Draw i seguenti diagrammi:
- UC2;
- UC2.4:
- UC2.5.1;

Ridimensionare inoltre i seguenti diagrammi:
- UC1.2;
- UC2;
- UC2.4:
- UC2.5.1;

**Comment by meneghinello-andrea** [comment]
UC2 ESPORTATO;
UC2.4 ESPORTATO;
UC2.5.1 ESPORTATO;

Rimangono da ridimensionare i diagrammi sopra citati.

**Comment by B1uRay** [comment]
ridimensionati correttamente
UC2
UC2.4
UC2.5.1
UC1.2
