### ISSUE TITLE
[AR] cambio destinazione di alcuni requisiti

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#73]
Sempre parlando dei requisiti nella sezione della qualità sono da spostare i seguenti requisiti:
- RSQO1.2.0 -> dovrebbe essere funzionale/dichiarativo;
- RSQO2.1.0 -> dovrebbe essere funzionale/dichiarativo;
- RSQD2.1.1 -> dovrebbe essere funzionale/dichiarativo;
- RDQD2.1.2 -> dovrebbe essere funzionale/dichiarativo;
- RSQD21.0.0 -> dovrebbe essere funzionale/dichiarativo;

**Comment by diegoberaldin** [comment]
Ricordarsi di modificare anche l'appendice del PdQ in maniera corrispondente!

**Comment by Rizzi-Andrea** [comment]
AGGIORNATI TUTTI E 5 I REQUISITI E LE LORO DIPENDENZE. AGGIORNATO PDQ. C'È PERÒ UN PUNTO INTERROGATIVO... LA MODIFICA DEL PDQ SU TALE PIANO... È COMPLETA? ATTENDO CONFERMA DEL RESPONSABILIE PER LA CHIUSURA DELL'ISSUES. this.wait();

**Comment by diegoberaldin** [comment]
Nell'appendice del PdQ sono citati:
- il numero totale dei requisiti, che a seguito della modifica risulta invariato :ok_woman: 
- il numero di requisiti funzionali obbligatori, che è stato correttamente portato da 20 a 22 perché ora comprende anche RSFO1.2.0 e RSFO2.1.0 :ok_woman: 
- il numero di requisiti funzionali desiderabili, che è stato portato da 5 a 7 perché ora comprende anche  RSFD2.1.1 e RSFD 2.1.2 :no_good: 

A me risulta che dovrebbe esserci **RSFD21.0.0** e che quindi dovrebbero essere 8 e non 7 i requisiti funzionali desiderabili. Se qualcuno ritiene che l'interfaccia in più lingue non sia una funzionalità ma una qualità (intesa come _accessibilità_) per favore lo dica esplicitamente così possiamo parlarne assieme! Altrimenti non so se devo interpretare questa mancanza come un parere contrario o come una svista :bomb: 

Inoltre, anche ammettendo che sia a posto la questione sul PdQ, resta il fatto che l'AR non è stata ancora aggiornata, nonostante ci fosse il "via libera" per una modifica sporca al file `tracciamenti.tex` senza aggiornare il DB, con tutte le conseguenze del caso (es. dover controllare poi a mano i tracciamenti veri e propri requisiti-use case e requisiti-componenti).

Infine, la modifica a cascata sui nomi dei requisiti si ripercuote sul tracciamento requisiti-test. Anche qui occorre intervenire a mano cambiando i valori delle prime due colonne della tabella.

C'è qualche motivo in particolare per cui queste ultime due cose non sono state fatte? Volevate che ne parlassimo tutti assieme?
