### ISSUE TITLE
[ST] frecce di dipendenza nel diagramma dei package

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#79]
Inserire frecce di dipendenza anche:
- dal package `org::softwaresynthesis::mytalk::server` a `org::softwaresynthesis::mytalk::clientpresenter`
- dal package `org::softwaresynthesis::mytalk::clientpresenter` a `org::softwaresynthesis::mytalk::clientview`

**Comment by diegoberaldin** [comment]
Sono state introdotte (da me) dipendenze circolari? :rage:

**Comment by diegoberaldin** [comment]
Risolto il problema: il diagramma non esiste più!

**Comment by Rizzi-Andrea** [comment]
Mh... bello XD
