### ISSUE TITLE
[ST] descrivere meglio relazioni fra classi

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#88]
Rispondere alle seguenti domande, cui riccardin dice che non diamo risposta nel documento:
- come si realizza DAO?
- quali classi partecipano a MVP?

**Comment by diegoberaldin** [comment]
A mio parere, allo stato attuale delle cose:
- alla prima domanda risponde la descrizione di CS01 - Gestione database nella sezione (6.1.1) ripresa in componenti che implementano DAO (9.2.3);
- alla seconda domanda si trova risposta nella nuova stesura di componenti che implementano MVP (9.5.3)

Qualcuno di passaggio mi dà il suo parere?

**Comment by Rizzi-Andrea** [comment]
Riscrivendo ieri alcune cose, e riguardando il lavoro totale, mi sa che manca ancora qualcosina per renderlo capibile al 100%, ma linea generale ci siamo. A migliorare un po' la spiegazione ci penso io ;)

**Comment by diegoberaldin** [comment]
@Rizzi-Andrea, il prof ci ha contestato ancora che non sono chiare le relazioni fra le classi quindi lascio aperta...
