### ISSUE TITLE
[ST] assegnare codice alle componenti architetturali

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#91]

**Comment by diegoberaldin** [comment]
Non so se è il caso, ma io proporrei:
- CS per i componenti del server
- CP per i componenti del presenter
- CV per i componenti della vista

In definitiva si dovrebbe ottenere un elenco del tipo:
- CS0 - Gestione database
- CS1 - Gestione connessione
- CS2- Gestione rubrica
- CS3 - Gestione stato
- CS4 - Gestione segreteria
- CS5 - Gestione chiamate
- CS5 - Façade del server
- CP0 - Gestione comunicazione
- CP1 - Gestione GUI
- CP2 - Rappresentazione dati
- CP3 - Façade del presenter
- CV0 - Gestione GUI

Una volta che avremo deciso i codici definitivi si potranno inserire nella ST ma anche nel sistema di tracciamento.

**Comment by diegoberaldin** [comment]
@Rizzi-Andrea tu che cosa ne dici? Avevo iniziato il discorso un giorno con te ma poi non ne abbiamo più parlato! E, comunque, è mai possibile che nessuno abbia un'idea di cosa fare?

**Comment by Rizzi-Andrea** [comment]
Sono d'accordo con il tuo sistema. Francamente mi sembra logico e pratico. Come unica agiunta, supponendo che in futuro nuove espansioni possano portare ad avere più di 9 componenti, indicherei il codice con 2 cifre: CP01 CP02. Ora però devo chiederti, è necessario aggiungere queste nuove informazioni come campo nel DB? Oppure la parte di ST interessata può supportare l'inserimento manuale di tali codici

**Comment by diegoberaldin** [comment]
Ok, d'accordo per la doppia cifra! Nella specifica c'è una parte da cambiare a mano ma posso farlo io senza problemi, ma resta il problema che i tracciamenti finali sono attualmente da buttare (perché ci sono nuove classi, nuovi componenti e classi che han cambiato nome) e che quindi c'è comunque da mettere mano al DB!

In ogni caso, invece del sistema di codici proposto da me potremmo anche usare il valore del campo `ID` nella tabella `Componenti` del nostro sistema di tracciamento (magari preceduto da C), che però salta da 7 a 12. Questo riduce il lavoro che c'è da fare sul DB a una quantità sopportabile?

**Comment by Rizzi-Andrea** [comment]
Questo Issues è da chiudere? C'è altro da fare in merito???

**Comment by diegoberaldin** [comment]
Hai ragione, chiudo! :)
