### ISSUE TITLE
[PdQ] spostare in appendice descrizione teorica SPY e CMMI

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#93]

**Comment by B1uRay** [comment]
corretto integrando la parte e rendendola più coerente con la parte in cui è ora.

**Comment by diegoberaldin** [comment]
Ok perfetto! Questo toglie di mezzo il problema di spostarlo in appendice perché non è più _fuffa_...
