### ISSUE TITLE
[PdQ] enunciare obiettivi di qualità di prodotto e di processo in modo esplicito

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#94]
E inserite vostre opinioni nel wiki

**Comment by B1uRay** [comment]
provo ad integrare la qualità di processo con quanto "recupero" in giro :-)

**Comment by B1uRay** [comment]
ho modificato la sezione sulla qualità di processo...non so sinceramente se è quello che voleva cardin...in ogni caso ora sicuramente è più approfondita.

**Comment by diegoberaldin** [comment]
@B1uRay ti ho lasciato i commenti relativi alle tue modifiche nella [pagina del commit](https://github.com/SoftwareSynthesis/SoftwareEngineeringProject/commit/0b9b60ea333cb8a98cfa8d2a35c99063051a415e)
Grazie per aver avuto il coraggio di mettere mano a quell'orrendo documento, meno male che ci sei tu! Quando hai letto i miei commenti e apportato eventuali modifiche se accogli le mie raccomandazioni, chiudi pure l'issue. Grazie!!
EDIT-OT: ti ho lasciato anche qualche commentino nel commit successivo..

**Comment by B1uRay** [comment]
ho completato la mia parte integrando la parte di "tecniche metriche e misure"...
Manca la parte relativa all'RP sul capitolo "dettaglio dell'esito delle revisioni" e nell'appendice la parte sulla verifica della progettazione di dettaglio e codifica.

**Comment by diegoberaldin** [comment]
Corrispondono a #102 e #103 rispettivamente, quindi questa può essere chiusa!
