### ISSUE TITLE
[PdP] aggiornare analisi dei rischi alla RQ

### ISSUE THREAD

**Issue by diegoberaldin** [SoftwareSynthesis/SoftwareEngineeringProject#95]

**Comment by diegoberaldin** [comment]
Rischio **Eventi metereologici estremi** da inserire!
Analisi:

```
public class Trenitalia extends Thread {
  private Object snow;
  public void run() {
     snow.wait();
  }
}
```

Probabilità: media
Impatto: 4
Strategia di gestione: Skype... d'oh!
Riscontro effettivo: a carnevale ogni scherzo vale!

**Comment by Rizzi-Andrea** [comment]
XD piccole perle di simpatia sparse negli issues... è la tua nuova strategia per invogliarci a leggerli tutti? XD ci stai riuscendo ;)... aggiungerei anche il rischio meteorite cmq... -.-'

**Comment by diegoberaldin** [comment]
Ho anch'io i miei segreti sulle strategie per farvi leggere tutto :smile_cat:
E cmq vada per il rischio meteorite!!
