### ISSUE TITLE
[DdP] crittografia in campo dati password

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#98]
Dopo aver scelto il DBMS che ospiterà il nostro database trovare il modo per criptare e decriptare un campo dati di tipo testo (vedi funzioni `encode(string)` e `decode(string)` di MySQL) e verificare la lunghezza della stringa criptata per correggere il campo dati password nelle tabelle della specifica tecnica.

**Comment by diegoberaldin** [comment]
Più che in ST direi che è una cosa da segnalare in DdP. Pertanto la segno come "remember" e cambio l'oggetto in maniera corrispondente.

**Comment by Rizzi-Andrea** [comment]
giusto per sapere... alla fine usiamo un md5 oppure un AES "semplificato"? Non per dire, ma vi ricordo che con il message digest non possiamo fare recupero della password :/

**Comment by meneghinello-andrea** [comment]
Dobbiamo utilizzare un tipo di protezione che permetta il reverse dell'operazione poiché come requisito abbiamo che l'utente deve poter ritrovare la password smarrita. Visto che come DBMS è stato scelto MySql direi che il tipo più appropriato è Char(41) poiché la funzione di codifica citata in testa  restituisce una stringa di 41 caratteri.

**Comment by meneghinello-andrea** [comment]
Il database attualmente è configurato per poter operare con le funzioni ''encode(string, string)'' e ''decode(string, string)'' di MySql che permettono di codificare e decodificare una stringa. (NON MOLTO SICURO come osservato assieme a riccardo). Adesso devo capire come configurare hibernate in modo tale che adoperi quelle funzioni in fase di insert e select. Cosa ne pensate @Rizzi-Andrea @diegoberaldin

**Comment by meneghinello-andrea** [comment]
Problema risolto utilizzando JAAS
