### ISSUE TITLE
[ST] inserire chiamate nel package DAO

### ISSUE THREAD

**Issue by meneghinello-andrea** [SoftwareSynthesis/SoftwareEngineeringProject#99]
Aggiungere una classe e relativa interfaccia per rappresentare le chiamate (oggetto `Call` e interfaccia `ICall`)

**Comment by diegoberaldin** [comment]
Non più in `server.dao` ma in un package `server.call` questo è ora inserito in ST. Inseriti anche `ICallDAO` e `MySQLCallDAO` nel package `dao`.
